# Generated by Django 2.2.10 on 2020-06-18 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0515_auto_20200519_1649'),
        ('learning_unit', '0003_centralmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralmanager',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Entity'),
        ),
        migrations.AlterField(
            model_name='centralmanager',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person'),
        ),
        migrations.CreateModel(
            name='FacultyManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_child', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                             to='base.Entity')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                             to='base.Person')),
            ],
            options={
                'verbose_name': 'Faculty manager',
                'verbose_name_plural': 'Faculty managers',
                'default_related_name': 'learning_unit',
            },
        ),
    ]
