# Generated by Django 2.2.13 on 2021-01-18 14:38
import datetime

from django.db import migrations
from django.utils import timezone

from base.models.enums.academic_calendar_type import AcademicCalendarTypes


def create_learning_unit_force_majeur_summary_edition_calendar(apps, shema_editor):
    """
    We will create all calendars which are mandatory to learning unit app
    """
    AcademicYear = apps.get_model('base', 'academicyear')
    AcademicCalendar = apps.get_model('base', 'academiccalendar')

    now = timezone.now()
    current_academic_year = AcademicYear.objects.filter(start_date__lte=now, end_date__gte=now).last()
    if current_academic_year:
        AcademicCalendar.objects.filter(
            academic_year__year__gte=2021,
            reference=AcademicCalendarTypes.SUMMARY_COURSE_SUBMISSION_FORCE_MAJEURE.name
        ).delete()

        qs = AcademicYear.objects.filter(year__gte=2021, year__lte=current_academic_year.year + 6)
        for targeted_academic_year in qs:
            AcademicCalendar.objects.update_or_create(
                reference=AcademicCalendarTypes.SUMMARY_COURSE_SUBMISSION_FORCE_MAJEURE.name,
                data_year=targeted_academic_year,
                defaults={
                    "title": "Edition fiches descriptives (cas de force majeure)",
                    "start_date": datetime.date(targeted_academic_year.year + 1, 6, 15),
                    "end_date": datetime.date(targeted_academic_year.year + 1, 6, 20),
                    "academic_year": targeted_academic_year  # To remove after refactoring
                }
            )


class Migration(migrations.Migration):

    dependencies = [
        ('learning_unit', '0006_auto_20210112_1041'),
    ]

    operations = [
        migrations.RunPython(create_learning_unit_force_majeur_summary_edition_calendar, migrations.RunPython.noop),
    ]
