# Generated by Django 2.2.13 on 2021-03-17 15:59

from django.db import migrations

from base.models.enums.academic_calendar_type import AcademicCalendarTypes


def update_title_learning_unit_summary_edition_calendar(apps, schema_editor):
    AcademicCalendar = apps.get_model('base', 'academiccalendar')
    AcademicCalendar.objects.filter(
        reference=AcademicCalendarTypes.SUMMARY_COURSE_SUBMISSION.name
    ).update(title="Modification fiches descriptives")


def update_title_learning_unit_force_majeur_summary_edition_calendar(apps, schema_editor):
    AcademicCalendar = apps.get_model('base', 'academiccalendar')
    AcademicCalendar.objects.filter(
        reference=AcademicCalendarTypes.SUMMARY_COURSE_SUBMISSION_FORCE_MAJEURE.name
    ).update(title="Modification fiches descriptives (cas de force majeure)")


class Migration(migrations.Migration):

    dependencies = [
        ('learning_unit', '0010_auto_20210115_1314'),
        ('base', '0581_auto_20210317_1620'),
    ]

    operations = [
        migrations.RunPython(update_title_learning_unit_summary_edition_calendar, migrations.RunPython.noop),
        migrations.RunPython(
            update_title_learning_unit_force_majeur_summary_edition_calendar,
            migrations.RunPython.noop
        ),
    ]
