# Generated by Django 2.2.13 on 2021-03-18 15:15

from django.db import migrations, models
import django.db.models.deletion


def migrate_student_worker_groups(apps, schema_editor):
    StudentWorker = apps.get_model('learning_unit', 'studentworker')
    Person = apps.get_model('base', 'Person')

    student_workers = Person.objects.filter(user__groups__name='student_update_UE_AA')
    for student_worker in student_workers:
        StudentWorker.objects.create(person=student_worker)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0580_merge_20210317_1414'),
        ('learning_unit', '0010_auto_20210115_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person')),
            ],
            options={
                'verbose_name': 'Student worker',
                'verbose_name_plural': 'Student workers',
            },
        ),
        migrations.RunPython(migrate_student_worker_groups, migrations.RunPython.noop),
    ]
