---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_paths:
      - "base/tests/**/*"
      - "admission/tests/**/*"
      - "attribution/tests/**/*"
      - "dissertation/tests/**/*"
      - "internship/tests/**/*"
    config:
      languages:
      - javascript
      - python
  eslint:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.py"
exclude_paths:
  - "base/migrations/**/*"
  - "base/static/js/**/*"
  - "base/static/css/**/*"
