# Generated by Django 2.2.13 on 2021-01-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_scoresheetaddress_education_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoresheetaddress',
            name='offer_year',
        ),
    ]
