# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-02 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_auto_20190128_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoresencoding',
            options={'managed': False, 'permissions': (('can_access_scoreencoding', 'Can access scoreencoding'), ('change_scoresresponsible', 'Can change scores responsible'), ('view_scoresresponsible', 'Can view scores responsible'))},
        ),
    ]
