from .content_read import GroupReadContent
from .create import GroupCreateView
from .general_information_read import GroupReadGeneralInformation
from .general_information_update import GroupUpdateGeneralInformation
from .identification_read import GroupReadIdentification
from .utilization_read import GroupReadUtilization
