# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-06 11:27
from __future__ import unicode_literals

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ('cms', '0001_initial'), ('cms', '0002_auto_20170316_1618'), ('cms', '0003_auto_20170317_1033'),
        ('cms', '0004_auto_20170425_1548'), ('cms', '0005_auto_20170516_1335'),
        ('cms', '0006_auto_20170516_1638'), ('cms', '0007_auto_20170607_1522'),
        ('cms', '0008_auto_20180212_0905'), ('cms', '0009_auto_20180327_1458'),
        ('cms', '0010_auto_20180327_1513'), ('cms', '0011_auto_20180417_1017'),
        ('cms', '0012_auto_20180807_1229')
    ]

    dependencies = [
        ('reference', '0015_educationinstitution_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('published', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             to='cms.TextLabel')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity',
                 models.CharField(choices=[('learning_unit_year', 'learning_unit_year'), ('offer_year', 'offer_year')],
                                  db_index=True, max_length=25)),
                ('reference', models.IntegerField(db_index=True)),
                ('text', ckeditor.fields.RichTextField(null=True)),
                ('language',
                 models.CharField(choices=[('fr-be', 'French'), ('en', 'English')], default='fr-be', max_length=30,
                                  null=True)),
                ('text_label', models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='cms.TextLabel')),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedTextLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('language',
                 models.CharField(choices=[('fr-be', 'French'), ('en', 'English')], default='fr-be', max_length=30,
                                  null=True)),
                ('text_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.TextLabel')),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='textlabel',
            unique_together=set([('parent', 'order')]),
        ),
        migrations.AlterField(
            model_name='textlabel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='cms.TextLabel'),
        ),
        migrations.AlterField(
            model_name='textlabel',
            name='order',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='textlabel',
            name='entity',
            field=models.CharField(choices=[('learning_unit_year', 'learning_unit_year'), ('offer_year', 'offer_year')],
                                   max_length=25),
        ),
        migrations.AlterField(
            model_name='textlabel',
            name='order',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='textlabel',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='textlabel',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        # Remove translated text related to learning achievements
        migrations.RunSQL("""
            DELETE FROM cms_translatedtext
            WHERE text_label_id in (
                SELECT id
                FROM cms_textlabel
                WHERE label = 'skills_to_be_acquired' AND entity = 'learning_unit_year'
            )
        """),
        # Remove translated text label related to learning achievements
        migrations.RunSQL("""
            DELETE FROM cms_translatedtextlabel
            WHERE text_label_id in (
                SELECT id
                FROM cms_textlabel
                WHERE label = 'skills_to_be_acquired' AND entity = 'learning_unit_year'
            )
        """),
        # Remove text label related to learning achievements
        migrations.RunSQL("""
            DELETE FROM cms_textlabel
            WHERE label = 'skills_to_be_acquired' AND entity = 'learning_unit_year'
        """),
        migrations.AlterField(
            model_name='textlabel',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='translatedtext',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='translatedtextlabel',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
