# Generated by Django 2.2.5 on 2019-10-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20191011_1133'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translatedtextlabel',
            unique_together={('language', 'text_label')},
        ),
    ]
