# Generated by Django 2.2.13 on 2020-06-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0002_auto_20191024_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textlabel',
            name='entity',
            field=models.CharField(choices=[('learning_unit_year', 'learning_unit_year'), ('offer_year', 'offer_year'),
                                            ('group_year', 'group_year')], max_length=25),
        ),
        migrations.AlterField(
            model_name='translatedtext',
            name='entity',
            field=models.CharField(choices=[('learning_unit_year', 'learning_unit_year'), ('offer_year', 'offer_year'),
                                            ('group_year', 'group_year')], db_index=True, max_length=25),
        ),
    ]
