# Generated by Django 2.2.13 on 2020-06-25 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cms', '0002_auto_20191024_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedtext',
            name='content_type',
            field=models.ForeignKey(
                limit_choices_to=models.Q(models.Q(('app_label', 'base'), ('model', 'education_group_year')),
                                          models.Q(('app_label', 'education_group'), ('model', 'group_year')),
                                          models.Q(('app_label', 'base'), ('model', 'learning_unit_year')),
                                          _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT,
                to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='translatedtext',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='translatedtext',
            unique_together={('entity', 'content_type', 'object_id', 'text_label', 'language')},
        ),
        migrations.RemoveField(
            model_name='translatedtext',
            name='reference',
        ),
    ]
