# Generated by Django 2.2.13 on 2020-06-24 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cms', '0002_auto_20191024_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedtext',
            name='reference_type',
            field=models.ForeignKey(
                limit_choices_to=models.Q(models.Q(('app_label', 'base'), ('model', 'education_group_year')),
                                          models.Q(('app_label', 'education_group'), ('model', 'group_year')),
                                          models.Q(('app_label', 'base'), ('model', 'learning_unit_year')),
                                          _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT,
                to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='translatedtext',
            name='reference',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='translatedtext',
            unique_together={('entity', 'reference_type', 'reference', 'text_label', 'language')},
        ),
    ]
