# Generated by Django 2.2.5 on 2020-01-07 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0489_auto_20191217_1505'),
        ('education_group', '0002_auto_20191224_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupyear',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.AcademicYear', verbose_name='Academic year'),
        ),
    ]
