# Generated by Django 2.2.5 on 2020-01-21 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0497_auto_20200108_1213'),
        ('education_group', '0003_groupyear_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupyear',
            name='management_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_management_entity', to='base.Entity', verbose_name='Management entity'),
        ),
    ]
