# Generated by Django 2.2.10 on 2020-06-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0516_auto_20200602_1440'),
        ('education_group', '0007_auto_20200416_1234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupyear',
            unique_together={('partial_acronym', 'academic_year')},
        ),
    ]
