# Generated by Django 2.2.13 on 2020-09-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_group', '0008_auto_20200618_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupyear',
            name='active',
        ),
    ]
