# Generated by Django 2.2.13 on 2020-10-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0541_auto_20201019_1604'),
        ('education_group', '0009_remove_groupyear_active'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='groupyear',
            index_together={('partial_acronym', 'academic_year')},
        ),
    ]
