# Generated by Django 3.1.1 on 2020-10-07 09:51

from django.db import migrations
from django.db.models import F


def fix_unsynchronized_title_english(apps, schema_editor):
    GroupYear = apps.get_model('education_group', 'GroupYear')
    group_years = GroupYear.objects.filter(
        academic_year__year__gte=2019,
        education_group_type__category__in=['TRAINING', 'MINI_TRAINING'],
        educationgroupversion__isnull=False
    ).exclude(
        educationgroupversion__offer__title_english=F('title_en')
    )
    for gy in group_years:
        gy.title_en = gy.educationgroupversion.offer.title_english
    GroupYear.objects.bulk_update(group_years, ['title_en'])


class Migration(migrations.Migration):
    dependencies = [
        ('education_group', '0011_auto_20201007_0951'),
    ]

    operations = [
        migrations.RunPython(fix_unsynchronized_title_english),
    ]
