# Generated by Django 2.2.13 on 2021-02-02 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_group', '0014_auto_20210112_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centraladmissionmanager',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_group_centraladmissionmanager_set', to='base.Person'),
        ),
        migrations.AlterField(
            model_name='centralmanager',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_group_centralmanager_set', to='base.Person'),
        ),
        migrations.AlterField(
            model_name='facultymanager',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_group_facultymanager_set', to='base.Person'),
        ),
    ]
