# Generated by Django 3.1.1 on 2020-11-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rules_management', '0003_auto_20180830_1558'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fieldreference',
            unique_together={('content_type', 'context', 'field_name')},
        ),
    ]
