# Generated by Django 2.2.5 on 2020-01-24 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0001_initial'),
        ('learning_unit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='learning_class_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='learning_unit.LearningClassYear', verbose_name='learning class year'),
        ),
    ]
