# Generated by Django 2.2.5 on 2020-03-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0506_remove_prerequisites_whithout_item'),
        ('program_management', '0003_educationgroupversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationgroupversion',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='educationgroupversion',
            managers=[
            ],
        ),
        migrations.AlterUniqueTogether(
            name='educationgroupversion',
            unique_together={('version_name', 'offer', 'is_transition')},
        ),
    ]
