# Generated by Django 2.2.5 on 2020-04-06 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0004_auto_20200323_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupversion',
            name='root_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='educationgroupversion', to='education_group.GroupYear', verbose_name='Root group'),
        ),
    ]
