# Generated by Django 2.2.10 on 2020-04-21 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0004_auto_20200323_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='group_year',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='education_group.GroupYear', verbose_name='group year'),
        ),
        migrations.AlterField(
            model_name='element',
            name='learning_class_year',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='learning_unit.LearningClassYear', verbose_name='learning class year'),
        ),
        migrations.AlterField(
            model_name='element',
            name='learning_unit_year',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.LearningUnitYear', verbose_name='learning unit year'),
        ),
    ]
