# Generated by Django 2.2.10 on 2020-04-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0005_auto_20200421_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupversion',
            name='root_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='educationgroupversion', to='education_group.GroupYear', verbose_name='Root group'),
        ),
    ]
