# Generated by Django 2.2.10 on 2020-04-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0005_auto_20200421_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupversion',
            name='title_en',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Title in English'),
        ),
        migrations.AlterField(
            model_name='educationgroupversion',
            name='title_fr',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Title in French'),
        ),
    ]
