# Generated by Django 2.2.13 on 2020-08-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0007_auto_20200424_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='education_group_year',
        ),
        migrations.AddConstraint(
            model_name='element',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('group_year__isnull', False), ('learning_unit_year__isnull', True), ('learning_class_year__isnull', True)), models.Q(('group_year__isnull', True), ('learning_unit_year__isnull', False), ('learning_class_year__isnull', True)), models.Q(('group_year__isnull', True), ('learning_unit_year__isnull', True), ('learning_class_year__isnull', False)), _connector='OR'), name='only_one_fk_element'),
        ),
    ]
