# Generated by Django 2.2.13 on 2021-03-05 15:06
import uuid

from django.db import migrations
from django.db.models import Q

from base.models.education_group_year import EducationGroupYear
from education_group.models.group_year import GroupYear


def clean_offers_without_version(apps, schema_editor):
    problematic_egys = find_problematic_egys()
    print("Problematic EducationGroupYears: {}".format(len(problematic_egys)))

    delete_offers_before_2019(problematic_egys)
    create_missing_version_and_group_after_2018(problematic_egys)


def create_missing_version_and_group_after_2018(problematic_egys):
    after_2018_egys = problematic_egys.filter(academic_year__year__gt=2018)
    print("Creating {} missing Versions & Groups (after 2018)".format(len(after_2018_egys)))
    for egy in after_2018_egys:
        print("\tCreating {} {}".format(egy.acronym, egy.academic_year.year))
        previous_egy = egy.education_group.educationgroupyear_set.get(academic_year__year=egy.academic_year.year - 1)
        version = previous_egy.educationgroupversion_set.get(version_name='', is_transition=False)
        group = _get_or_create_group(egy, version)
        _create_version(egy, group, version)


def _create_version(egy, group, version):
    version.pk = None
    version.external_id = None
    version.uuid = uuid.uuid4()
    version.root_group = group
    version.offer = egy
    version.save()


def _get_or_create_group(egy, version):
    existing_group = GroupYear.objects.filter(
        academic_year=egy.academic_year,
        partial_acronym=egy.partial_acronym
    )
    if not existing_group:
        print("\tCreating new group")
        group = version.root_group
        group.pk = None
        group.external_id = None
        group.uuid = uuid.uuid4()
        group.academic_year = egy.academic_year
        group.save()
    else:
        print("\tUsing existing group")
        group = existing_group.first()
    return group


def delete_offers_before_2019(problematic_egys):
    before_2019_egys = problematic_egys.filter(academic_year__year__lt=2019)
    print("Deleting {} EducationGroupYears without version (before 2019) : ".format(len(before_2019_egys)))
    for egy in before_2019_egys:
        print("\tDeleting {} {}".format(egy.acronym, egy.academic_year.year))
        _delete_enrollments(egy)
    before_2019_egys.delete()


def _delete_enrollments(egy):
    offer_enrollments = egy.offerenrollment_set.all()
    if offer_enrollments:
        print("\t\t Deleting {} OfferEnrollments".format(len(offer_enrollments)))
        offer_enrollments.delete()


def find_problematic_egys():
    return EducationGroupYear.objects.filter(
        educationgroupversion__isnull=True
    ).exclude(
        Q(acronym__icontains='11BA') | Q(acronym__icontains='common')
    ).prefetch_related(
        'offerenrollment_set',
    ).order_by('academic_year__year')


class Migration(migrations.Migration):
    dependencies = [
        ('program_management', '0008_auto_20200826_0835'),
    ]

    operations = [
        migrations.RunPython(clean_offers_without_version),
    ]
