# Generated by Django 2.2.13 on 2020-08-26 08:35

from django.db import migrations, models
import script


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0008_auto_20200826_0835'),
    ]

    operations = [
        migrations.RunPython(script.fix_order)
    ]
