# Generated by Django 2.2.13 on 2021-02-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0008_auto_20200826_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroupversion',
            name='transition_name',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Transition name'),
        ),
    ]
