# Generated by Django 2.2.13 on 2021-02-08 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0565_auto_20210203_1310'),
        ('program_management', '0009_educationgroupversion_transition_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='educationgroupversion',
            unique_together={('version_name', 'offer', 'transition_name')},
        ),
        migrations.RemoveField(
            model_name='educationgroupversion',
            name='is_transition',
        ),
    ]
