# Generated by Django 2.2.10 on 2020-04-15 16:05
import uuid

from django.db import migrations, models


def populate_uuid_domain_isced(apps, schema_editor):
    domain_isced_mdl = apps.get_model("reference", "DomainIsced")
    domain_isced_items = domain_isced_mdl.objects.all()

    for item in domain_isced_items:
        item.uuid = uuid.uuid4()
        item.save()


class Migration(migrations.Migration):
    dependencies = [
        ('reference', '0002_auto_20190308_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainisced',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(populate_uuid_domain_isced, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='domainisced',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, db_index=True, editable=False, unique=True),
        ),
    ]
