# Generated by Django 2.2.10 on 2020-05-05 16:38

from django.db import migrations, models


def forward(apps, schema_editor):
    DomainIsced = apps.get_model('reference', 'DomainIsced')
    DomainIsced.objects.filter(code='0111').update(
        title_en="Education science"
    )


class Migration(migrations.Migration):
    dependencies = [
        ('reference', '0003_domainisced_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainisced',
            name='is_ares',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(forward, migrations.RunPython.noop)
    ]
