# Generated by Django 2.2.5 on 2019-12-06 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0037_auto_20181116_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributionchargenew',
            name='allocation_charge',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
