# Generated by Django 2.2.5 on 2020-03-19 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0038_auto_20191206_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorapplication',
            name='learning_container_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.LearningContainerYear'),
        ),
    ]
