# Generated by Django 2.2.13 on 2021-01-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0041_auto_20210121_1336'),
        ('attribution', '0041_auto_20210115_1109'),
    ]

    operations = [
    ]
