# Generated by Django 2.2.13 on 2021-02-24 11:37
import datetime

from django.db import migrations
from django.utils import timezone

from base.models.enums.academic_calendar_type import AcademicCalendarTypes


def create_access_schedule_calendar(apps, shema_editor):
    AcademicYear = apps.get_model('base', 'academicyear')
    AcademicCalendar = apps.get_model('base', 'academiccalendar')

    now = timezone.now()
    current_academic_year = AcademicYear.objects.filter(start_date__lte=now, end_date__gte=now).last()
    if current_academic_year:
        qs = AcademicYear.objects.filter(year__gte=2020, year__lte=current_academic_year.year + 6)
        for ac_year in qs:
            AcademicCalendar.objects.update_or_create(
                reference=AcademicCalendarTypes.ACCESS_SCHEDULE_CALENDAR.name,
                data_year=ac_year,
                defaults={
                    "title": "Accès horaire ADE",
                    "start_date": datetime.date(ac_year.year, 7, 1),
                    "end_date": datetime.date(ac_year.year + 1, 9, 14),
                    "academic_year": ac_year
                }
            )


def remove_access_schedule_calendar(apps, shema_editor):
    AcademicCalendar = apps.get_model('base', 'academiccalendar')
    AcademicCalendar.objects.filter(reference=AcademicCalendarTypes.ACCESS_SCHEDULE_CALENDAR.name).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0042_merge_20210126_0900'),
    ]

    operations = [
        migrations.RunPython(create_access_schedule_calendar, remove_access_schedule_calendar),
    ]
