# Generated by Django 2.2.14 on 2021-03-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0043_auto_20210224_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribution',
            name='uuid',
        ),
    ]
