# Generated by Django 2.2.13 on 2021-05-03 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0045_auto_20210318_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorapplication',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
