# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0024_internshipspeciality_order_postion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipoffer',
            name='master',
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='internship_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipMaster'),
        ),
        migrations.RemoveField(
            model_name='internshipmaster',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='internshipmaster',
            name='type_mastery',
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='cremec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='date_end_activity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='date_start_activity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='email_private',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='email_professionnal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='phone_private',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='phone_professionnal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='sexe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
