# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0024_internshipspeciality_order_postion'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipstudentaffectationstat',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
