from .common import CommonGeneralInformation, UpdateCommonGeneralInformation
from .common_bachelor import CommonBachelorAdmissionCondition, UpdateCommonBachelorAdmissionCondition
from .common_aggregate import CommonAggregateAdmissionCondition, UpdateCommonAggregateAdmissionCondition
from .common_master import CommonMasterAdmissionCondition, UpdateCommonMasterAdmissionCondition
from .common_master_specialized import CommonMasterSpecializedAdmissionCondition, \
    UpdateCommonMasterSpecializedAdmissionCondition
from .publish import publish_common_admission_conditions, publish_common_pedagogy
