# Generated by Django 2.2.5 on 2020-01-04 01:17

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('base', '0087_uuid_not_null'), ('base', '0088_auto_20170106_1728')]

    dependencies = [
        ('base', '0086_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunitcomponent',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='learningunitenrollment',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='learningunit',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='in_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='vacant',
            field=models.BooleanField(default=False),
        ),
    ]
