# Generated by Django 2.2.5 on 2020-01-04 01:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('base', '0090_uuid_not_null'), ('base', '0091_academiccalendar_uuid')]

    dependencies = [
        ('base', '0089_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunit',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
    ]
