# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 12:29
from __future__ import unicode_literals

from django.db import migrations


def remove_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    db_alias = schema_editor.connection.alias
    Group.objects.using(db_alias).filter(name="internship_students").delete()
    Group.objects.using(db_alias).filter(name="students").delete()


def rollback_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    db_alias = schema_editor.connection.alias
    Group.objects.using(db_alias).bulk_create([
        Group(name="internship_students"),
        Group(name="students")
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0098_auto_20170306_0953'),
    ]

    operations = [
        migrations.RunPython(remove_groups, rollback_groups),
    ]
