# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-22 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0099_auto_20170320_1329'),
        ('base', '0099_auto_20170320_1114'),
    ]

    operations = [
    ]
