# Generated by Django 2.2.5 on 2020-01-04 01:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('base', '0121_auto_20170518_0959'), ('base', '0122_auto_20170524_1538'), ('base', '0123_auto_20170529_1451'), ('base', '0124_entity_models_update'), ('base', '0125_auto_20170529_1004'), ('base', '0126_auto_20170530_1401'), ('base', '0127_auto_20170530_1716'), ('base', '0128_auto_20170601_1345'), ('base', '0129_auto_20170601_1542'), ('base', '0130_learningcontaineryear_campus'), ('base', '0131_auto_20170602_1745'), ('base', '0132_learningclassyear_description'), ('base', '0133_auto_20170607_1451'), ('base', '0134_entity_models_update'), ('base', '0135_auto_20170616_0850'), ('base', '0136_auto_20170619_1107'), ('base', '0137_auto_20170620_1042'), ('base', '0138_auto_20170626_0938'), ('base', '0139_learningcontainer_start_year'), ('base', '0140_auto_20170627_1516'), ('base', '0141_auto_20170703_0957'), ('base', '0142_auto_20170718_1145'), ('base', '0143_educationgroup_educationgroupyear_groupelementyear'), ('base', '0144_auto_20170719_1417'), ('base', '0145_auto_20170801_1550'), ('base', '0146_remove_person_national_id'), ('base', '0147_auto_20170810_1330'), ('base', '0148_auto_20170821_0931'), ('base', '0149_auto_20170830_0958'), ('base', '0150_learningcomponentyear_hourly_volume_partial'), ('base', '0151_remove_learningunit_description'), ('base', '0152_auto_20170905_1317'), ('base', '0153_education_group_year_new_fields'), ('base', '0154_auto_20170906_1637'), ('base', '0155_auto_20170908_1551'), ('base', '0156_offeryearentity_education_group_year')]

    dependencies = [
        ('base', '0120_students_groups'),
        ('reference', '0016_auto_20170410_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningcomponentyear',
            old_name='hourly_volume_Q1',
            new_name='hourly_volume_partial',
        ),
        migrations.RemoveField(
            model_name='learningcomponent',
            name='learning_container',
        ),
        migrations.RemoveField(
            model_name='learningclassyear',
            name='learning_class',
        ),
        migrations.RemoveField(
            model_name='learningcomponentyear',
            name='learning_component',
        ),
        migrations.AlterField(
            model_name='learningcomponentyear',
            name='type',
            field=models.CharField(blank=True, choices=[('LECTURING', 'LECTURING'), ('STAGE', 'STAGE'), ('DISSERTATION', 'DISSERTATION'), ('PRACTICAL_EXERCISES', 'PRACTICAL_EXERCISES'), ('OTHER', 'OTHER')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='LearningClass',
        ),
        migrations.DeleteModel(
            name='LearningComponent',
        ),
        migrations.AddField(
            model_name='learningcomponentyear',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='learningcomponentyear',
            name='type',
            field=models.CharField(blank=True, choices=[('LECTURING', 'LECTURING'), ('STAGE', 'STAGE'), ('DISSERTATION', 'DISSERTATION'), ('PRACTICAL_EXERCISES', 'PRACTICAL_EXERCISES')], max_length=30, null=True),
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'entities'},
        ),
        migrations.AlterModelOptions(
            name='entityaddress',
            options={'verbose_name_plural': 'entity addresses'},
        ),
        migrations.AddField(
            model_name='entity',
            name='external_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='entitylink',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_parent', to='base.Entity'),
        ),
        migrations.AlterField(
            model_name='entitylink',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to_children', to='base.Entity'),
        ),
        migrations.AlterField(
            model_name='entitylink',
            name='end_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='end_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Language'),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='title_english',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='title_english',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='acronym',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organizationaddress',
            name='changed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='organizationaddress',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='reference',
            new_name='prefix',
        ),
        migrations.AddField(
            model_name='entity',
            name='changed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='entityversion',
            name='changed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='entityversion',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Campus'),
        ),
        migrations.AlterField(
            model_name='learningcomponentyear',
            name='type',
            field=models.CharField(blank=True, choices=[('LECTURING', 'LECTURING'), ('PRACTICAL_EXERCISES', 'PRACTICAL_EXERCISES')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='container_type',
            field=models.CharField(blank=True, choices=[('COURSE', 'COURSE'), ('INTERNSHIP', 'INTERNSHIP'), ('DISSERTATION', 'DISSERTATION'), ('OTHER_COLLECTIVE', 'OTHER_COLLECTIVE'), ('OTHER_INDIVIDUAL', 'OTHER_INDIVIDUAL'), ('MASTER_THESIS', 'MASTER_THESIS'), ('EXTERNAL', 'EXTERNAL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='subtype',
            field=models.CharField(blank=True, choices=[('FULL', 'FULL'), ('PARTIM', 'PARTIM'), ('INTERNSHIP', 'INTERNSHIP'), ('TEACHING_INTERNSHIP', 'TEACHING_INTERNSHIP'), ('CLINICAL_INTERNSHIP', 'CLINICAL_INTERNSHIP'), ('PROFESSIONAL_INTERNSHIP', 'PROFESSIONAL_INTERNSHIP'), ('RESEARCH_INTERNSHIP', 'RESEARCH_INTERNSHIP')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='learningclassyear',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learningclassyear',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunSQL(
            sql="\n            DO\n            $$\n            DECLARE\n                trigger_to_remove record;\n            BEGIN\n                FOR trigger_to_remove IN SELECT distinct(event_object_table), trigger_name from information_schema.triggers where trigger_name LIKE 'update_%_modtime' LOOP\n                    EXECUTE 'DROP TRIGGER ' || trigger_to_remove.trigger_name || ' ON ' || trigger_to_remove.event_object_table || ';';\n                END LOOP;\n            END;\n            $$ language 'plpgsql';\n            ",
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='attribution',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='externaloffer',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningcontainer',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningunitenrollment',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerenrollment',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='offeryear',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='offeryearcalendar',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='offeryeardomain',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationaddress',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='programmanager',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionexam',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionexamcalendar',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionexamdeadline',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RemoveField(
            model_name='entitylink',
            name='child',
        ),
        migrations.RemoveField(
            model_name='entitylink',
            name='parent',
        ),
        migrations.AddField(
            model_name='entity',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entityversion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_of', to='base.Entity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Organization'),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_of', to='base.Entity'),
        ),
        migrations.DeleteModel(
            name='EntityAddress',
        ),
        migrations.DeleteModel(
            name='EntityLink',
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='acronym',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Entity'),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('SECTOR', 'SECTOR'), ('FACULTY', 'FACULTY'), ('SCHOOL', 'SCHOOL'), ('INSTITUTE', 'INSTITUTE'), ('POLE', 'POLE'), ('DOCTORAL_COMMISSION', 'DOCTORAL_COMMISSION'), ('PLATFORM', 'PLATFORM'), ('LOGISTICS_ENTITY', 'LOGISTICS_ENTITY')], db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelOptions(
            name='entitymanager',
            options={},
        ),
        migrations.CreateModel(
            name='EntityContainerYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('REQUIREMENT_ENTITY', 'REQUIREMENT_ENTITY'), ('ALLOCATION_ENTITY', 'ALLOCATION_ENTITY'), ('ADDITIONAL_REQUIREMENT_ENTITY_1', 'ADDITIONAL_REQUIREMENT_ENTITY_1'), ('ADDITIONAL_REQUIREMENT_ENTITY_2', 'ADDITIONAL_REQUIREMENT_ENTITY_2')], max_length=35)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Entity')),
                ('learning_container_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningContainerYear')),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'unique_together': {('entity', 'learning_container_year', 'type')},
            },
        ),
        migrations.AddField(
            model_name='learningcontainer',
            name='auto_renewal_until',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='EntityComponentYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_volume_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hourly_volume_partial', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('entity_container_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.EntityContainerYear')),
                ('learning_component_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningComponentYear')),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='learningcomponentyear',
            name='hourly_volume_partial',
        ),
        migrations.RemoveField(
            model_name='learningcomponentyear',
            name='hourly_volume_total',
        ),
        migrations.DeleteModel(
            name='ApplicationNotice',
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(blank=True, choices=[('MAIN', 'MAIN'), ('ACADEMIC_PARTNER', 'ACADEMIC_PARTNER'), ('INDUSTRIAL_PARTNER', 'INDUSTRIAL_PARTNER'), ('SERVICE_PARTNER', 'SERVICE_PARTNER'), ('COMMERCE_PARTNER', 'COMMERCE_PARTNER'), ('PUBLIC_PARTNER', 'PUBLIC_PARTNER')], default='UNKNOWN', max_length=30, null=True),
        ),
        migrations.AlterModelOptions(
            name='learningunit',
            options={'permissions': (('can_access_learningunit', 'Can access learning unit'), ('can_edit_learningunit_pedagogy', 'Can edit learning unit pedagogy'), ('can_edit_learningunit_specification', 'Can edit learning unit specification'))},
        ),
        migrations.AddField(
            model_name='learningcontainer',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
        migrations.RenameField(
            model_name='learningunitcomponentclass',
            old_name='learning_unit_year',
            new_name='learning_class_year',
        ),
        migrations.AlterField(
            model_name='organizationaddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Attribution',
        ),
        migrations.CreateModel(
            name='EducationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationGroupYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('acronym', models.CharField(db_index=True, max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AcademicYear')),
                ('education_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroup')),
                ('education_group_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.OfferType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupElementYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('child_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_branch', to='base.EducationGroupYear')),
                ('child_leaf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_leaf', to='base.EducationGroupYear')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='base.EducationGroupYear')),
                ('learning_unit_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnitYear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='internship_subtype',
            field=models.CharField(blank=True, choices=[('TEACHING_INTERNSHIP', 'TEACHING_INTERNSHIP'), ('CLINICAL_INTERNSHIP', 'CLINICAL_INTERNSHIP'), ('PROFESSIONAL_INTERNSHIP', 'PROFESSIONAL_INTERNSHIP'), ('RESEARCH_INTERNSHIP', 'RESEARCH_INTERNSHIP')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='learningunityear',
            name='activity_status',
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='subtype',
            field=models.CharField(blank=True, choices=[('FULL', 'FULL'), ('PARTIM', 'PARTIM')], max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='person',
            name='national_id',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('can_access_student', 'Can access student'),)},
        ),
        migrations.AlterField(
            model_name='learningcomponentyear',
            name='acronym',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='learningunit',
            name='faculty_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningunit',
            name='other_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='session',
            field=models.CharField(blank=True, choices=[('P23', 'P23'), ('3', '3'), ('2', '2'), ('23', '23'), ('1', '1'), ('13', '13'), ('12', '12'), ('123', '123')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='learningcomponentyear',
            name='hourly_volume_partial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.RemoveField(
            model_name='learningunit',
            name='description',
        ),
        migrations.RunSQL(
            sql='UPDATE base_entity SET country = NULL',
        ),
        migrations.AddField(
            model_name='entity',
            name='fax',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Country'),
        ),
        migrations.RemoveField(
            model_name='educationgroup',
            name='uuid',
        ),
        migrations.AddField(
            model_name='educationgroup',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationgroup',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='educationgroupyear',
            name='uuid',
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='academic_type',
            field=models.CharField(blank=True, choices=[('NON_ACADEMIC', 'NON_ACADEMIC'), ('NON_ACADEMIC_CREF', 'NON_ACADEMIC_CREF'), ('ACADEMIC', 'ACADEMIC')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='active',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('RE_REGISTRATION', 'RE_REGISTRATION')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='admission_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='diploma_printing_orientation',
            field=models.CharField(blank=True, choices=[('NO_PRINT', 'NO_PRINT'), ('IN_HEADING_2_OF_DIPLOMA', 'IN_HEADING_2_OF_DIPLOMA'), ('IN_EXPECTED_FORM', 'IN_EXPECTED_FORM')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='diploma_printing_title',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='dissertation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='english_activities',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('OPTIONAL', 'OPTIONAL')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='enrollment_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='base.Campus'),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='fee_type',
            field=models.CharField(blank=True, choices=[('FEE_1', 'FEE_1'), ('FEE_2', 'FEE_2'), ('FEE_3', 'FEE_3'), ('FEE_4', 'FEE_4'), ('FEE_5', 'FEE_5'), ('FEE_6', 'FEE_6'), ('FEE_7', 'FEE_7'), ('FEE_8', 'FEE_8'), ('FEE_10', 'FEE_10'), ('FEE_11', 'FEE_11'), ('FEE_12', 'FEE_12'), ('FEE_13', 'FEE_13')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='funding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='funding_cud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='funding_direction',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='funding_direction_cud',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='inter_organization_information',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='internship',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('OPTIONAL', 'OPTIONAL')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='joint_diploma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='main_teaching_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching', to='base.Campus'),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='other_campus_activities',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('OPTIONAL', 'OPTIONAL')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='other_language_activities',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('OPTIONAL', 'OPTIONAL')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='partial_deliberation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='professional_title',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='schedule_type',
            field=models.CharField(choices=[('DAILY', 'DAILY'), ('SHIFTED', 'SHIFTED'), ('ADAPTED', 'ADAPTED')], default='DAILY', max_length=20),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='university_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offeryeardomain',
            name='education_group_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupYear'),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='inter_university_abroad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='inter_university_belgium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='inter_university_french_community',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='primary_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Language'),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='highlight_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='session',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('12', '12'), ('13', '13'), ('23', '23'), ('123', '123'), ('P23', 'P23')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='OfferYearEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('ENTITY_ADMINISTRATION', 'ENTITY_ADMINISTRATION'), ('ENTITY_MANAGEMENT', 'ENTITY_MANAGEMENT')], max_length=30, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Entity')),
                ('offer_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.OfferYear')),
                ('education_group_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupYear')),
            ],
            options={
                'unique_together': {('offer_year', 'type')},
            },
        ),
    ]
