# Generated by Django 2.2.5 on 2020-01-04 01:21

import uuid

import django.db.models.deletion
from django.db import migrations, models

import base.models.enums.diploma_coorganization
import base.models.enums.duration_unit


class Migration(migrations.Migration):

    replaces = [('base', '0159_learning_component_year_not_null'), ('base', '0160_auto_20170926_0828'), ('base', '0161_new_fields_educationgroupyear'), ('base', '0162_educationgroup_permissions'), ('base', '0163_auto_20170919_1116'), ('base', '0164_educationgroupyear_category'), ('base', '0165_auto_20171009_1432'), ('base', '0166_educationgrouporganization'), ('base', '0167_offerenrollment_enrollment_state'), ('base', '0168_auto_20171018_1045'), ('base', '0169_student_academic_enrollment_state'), ('base', '0170_remove_student_academic_enrollment_state'), ('base', '0171_auto_20171017_1132'), ('base', '0172_learningunityear_quadrimester'), ('base', '0173_auto_20171027_1646')]

    dependencies = [
        ('reference', '0016_auto_20170410_1318'),
        ('base', '0158_learning_unit_component_clean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunitcomponent',
            name='learning_component_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningComponentYear'),
        ),
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['year'], 'permissions': (('can_access_academicyear', 'Can access academic year'),)},
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('QUADRIMESTER', 'QUADRIMESTER'), ('TRIMESTER', 'TRIMESTER'), ('MONTH', 'MONTH'), ('WEEK', 'WEEK'), ('DAY', 'DAY')], default=base.models.enums.duration_unit.DurationUnits('QUADRIMESTER'), max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='keywords',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='title_english',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='enrollment_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelOptions(
            name='educationgroup',
            options={'permissions': (('can_access_education_group', 'Can access education_group'),)},
        ),
        migrations.AlterUniqueTogether(
            name='entitycomponentyear',
            unique_together={('entity_container_year', 'learning_component_year')},
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='category',
            field=models.CharField(blank=True, choices=[('TRAINING', 'TRAINING'), ('MINI_TRAINING', 'MINI_TRAINING'), ('GROUP', 'GROUP')], max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='groupelementyear',
            name='learning_unit_year',
        ),
        migrations.RemoveField(
            model_name='groupelementyear',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='groupelementyear',
            name='child_leaf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_leaf', to='base.LearningUnitYear'),
        ),
        migrations.CreateModel(
            name='EducationGroupOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_students', models.BooleanField(default=False)),
                ('enrollment_place', models.BooleanField(default=False)),
                ('diploma', models.CharField(choices=[('UNIQUE', 'UNIQUE'), ('SEPARATE', 'SEPARATE'), ('NOT_CONCERNED', 'NOT_CONCERNED')], default=base.models.enums.diploma_coorganization.DiplomaCoorganizationTypes('NOT_CONCERNED'), max_length=40)),
                ('education_group_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupYear')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Organization')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos'),
        ),
        migrations.AddField(
            model_name='offerenrollment',
            name='enrollment_state',
            field=models.CharField(blank=True, choices=[('SUBSCRIBED', 'SUBSCRIBED'), ('PROVISORY', 'PROVISORY')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='language_association',
            field=models.CharField(blank=True, choices=[('OR', 'OR'), ('AND', 'AND')], max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='EducationGroupLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PRIMARY_LANGUAGE', 'PRIMARY_LANGUAGE')], max_length=255)),
                ('order', models.IntegerField()),
                ('education_group_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupYear')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.Language')),
            ],
        ),
        migrations.AddField(
            model_name='campus',
            name='code',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='is_administration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='quadrimester',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q1&2', 'Q1&2'), ('Q1|2', 'Q1|2')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='learningcomponentyear',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
    ]
