# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-13 08:31
from __future__ import unicode_literals

import base.models.entity_component_year
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0164_educationgroupyear_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitycomponentyear',
            name='hourly_volume_partial',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='entitycomponentyear',
            name='hourly_volume_total',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
