# Generated by Django 2.2.5 on 2020-01-04 01:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('base', '0175_auto_20171027_1702'), ('base', '0176_auto_20171027_1708'), ('base', '0177_learningcomponentyear_volume_declared_vacant'), ('base', '0178_auto_20171031_1544'), ('base', '0179_learningcontainer_uuid')]

    dependencies = [
        ('base', '0174_auto_20171027_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcomponentyear',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='learningunityear',
            name='in_charge',
        ),
        migrations.RemoveField(
            model_name='learningunityear',
            name='team',
        ),
        migrations.RemoveField(
            model_name='learningunityear',
            name='vacant',
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='in_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningcomponentyear',
            name='volume_declared_vacant',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='is_vacant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='type_declaration_vacant',
            field=models.CharField(blank=True, choices=[('RESEVED_FOR_INTERNS', 'RESEVED_FOR_INTERNS'), ('OPEN_FOR_EXTERNS', 'OPEN_FOR_EXTERNS'), ('EXCEPTIONAL_PROCEDURE', 'EXCEPTIONAL_PROCEDURE'), ('VACANT_NOT_PUBLISH', 'VACANT_NOT_PUBLISH'), ('DO_NOT_ASSIGN', 'DO_NOT_ASSIGN')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learningcontainer',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
    ]
