# Generated by Django 2.2.5 on 2020-01-04 01:22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('base', '0181_removed_nullable_uuid'), ('base', '0182_programmanager_education_group'), ('base', '0183_mandate_offer_calendar_date'), ('base', '0184_auto_20171106_1203')]

    dependencies = [
        ('base', '0180_populate_learning_container_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcontainer',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='programmanager',
            name='education_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroup'),
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('function', models.CharField(choices=[('PRESIDENT', 'PRESIDENT'), ('SECRETARY', 'SECRETARY'), ('SIGNATORY', 'SIGNATORY')], max_length=20)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('education_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Mandatary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Mandate')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
            ],
        ),
        migrations.AddField(
            model_name='offeryearcalendar',
            name='education_group_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupYear'),
        ),
        migrations.AlterField(
            model_name='offeryearcalendar',
            name='start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='offeryearcalendar',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='partial_acronym',
            field=models.CharField(db_index=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='remark_english',
            field=models.TextField(blank=True, null=True),
        ),
    ]
