# Generated by Django 2.2.5 on 2020-01-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('base', '0186_message_templates_learning_unit_deletion'), ('base', '0187_auto_20171120_1551'), ('base', '0188_auto_20171121_0948')]

    dependencies = [
        ('base', '0185_programmanager_link_to_education_group'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[('INSERT INTO osis_common_messagetemplate (reference, subject, template, format, language) VALUES (%s, %s, %s, %s, %s);', ['learning_unit_year_deletion_html', "Suppression de l'unité d'enseignement {learning_unit_acronym}", "{% autoescape off %}\r\n<p>Bonjour {{ first_name }} {{ last_name }},<br />\r\nCeci est un message automatique généré par le serveur OSIS – Merci de ne pas y répondre.<br />\r\n<br />\r\nVous avez demandé la suppression de l'UE {{ learning_unit_year }} {% if academic_year %}à partir de l'année {{ academic_year }}{% endif %}:<br />\r\n<ul>{% for msg in msg_list%}<li>{{ msg }}</li>{% endfor %}</ul>\r\n<br />\r\nCordialement,<br />\r\nOsis UCLouvain<br /></p>\r\n{% endautoescape %}", 'HTML', 'fr-be'])],
        ),
        migrations.RunSQL(
            sql=[('INSERT INTO osis_common_messagetemplate (reference, subject, template, format, language) VALUES (%s, %s, %s, %s, %s);', ['learning_unit_year_deletion_txt', "Suppression de l'unité d'enseignement {learning_unit_acronym}", "<p>Bonjour {{ first_name }} {{ last_name }},<br />\r\nCeci est un message automatique généré par le serveur OSIS – Merci de ne pas y répondre.<br />\r\n<br />\r\nVous avez demandé la suppression de l'UE {{ learning_unit_year }} {% if academic_year %}à partir de l'année {{ academic_year }}{% endif %}:<br />\r\n<ul>{% for msg in msg_list%}<li>{{ msg }}</li>{% endfor %}</ul>\r\n<br />\r\nCordialement,<br />\r\nOsis UCLouvain<br /></p>\r\n", 'PLAIN', 'fr-be'])],
        ),
        migrations.RunSQL(
            sql=[('INSERT INTO osis_common_messagetemplate (reference, subject, template, format, language) VALUES (%s, %s, %s, %s, %s);', ['learning_unit_year_deletion_html', 'Deletion of the learning unit {learning_unit_acronym}', '{% autoescape off %}\r\n<p>Hello {{ first_name }} {{ last_name }},<br />\r\nThis is an automatic message generated by the OSIS server – Please do not reply to this message.<br />\r\n<br />\r\nYou ask for the deletion of the learning unit {{ learning_unit_year }} {% if academic_year %}starting from the year {{ academic_year }}{% endif %}:<br />\r\n<ul>{% for msg in msg_list%}<li>{{ msg }}</li>{% endfor %}</ul>\r\n<br />\r\nRegards,<br />\r\nOsis UCLouvain<br /></p>\r\n{% endautoescape off %}', 'HTML', 'en'])],
        ),
        migrations.RunSQL(
            sql=[('INSERT INTO osis_common_messagetemplate (reference, subject, template, format, language) VALUES (%s, %s, %s, %s, %s);', ['learning_unit_year_deletion_txt', 'Deletion of the learning unit {learning_unit_acronym}', '<p>Hello {{ first_name }} {{ last_name }},<br />\r\nThis is an automatic message generated by the OSIS server – Please do not reply to this message.<br />\r\n<br />\r\nYou ask for the deletion of the learning unit {{ learning_unit_year }} {% if academic_year %}starting from the year{{ acadmic_year }}{% endif %}:<br />\r\n<ul>{% for msg in msg_list%}<li>{{ msg }}</li>{% endfor %}</ul>\r\n<br />\r\nRegards,<br />\r\nOsis UCLouvain<br /></p>\r\n', 'PLAIN', 'en'])],
        ),
        migrations.AlterModelOptions(
            name='learningunit',
            options={'permissions': (('can_access_learningunit', 'Can access learning unit'), ('can_edit_learningunit_pedagogy', 'Can edit learning unit pedagogy'), ('can_edit_learningunit_specification', 'Can edit learning unit specification'), ('can_delete_learningunit', 'Can delete learning unit'))},
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='reference',
            field=models.CharField(blank=True, choices=[('DELIBERATION', 'DELIBERATION'), ('DISSERTATION_SUBMISSION', 'DISSERTATION_SUBMISSION'), ('EXAM_ENROLLMENTS', 'EXAM_ENROLLMENTS'), ('SCORES_EXAM_DIFFUSION', 'SCORES_EXAM_DIFFUSION'), ('SCORES_EXAM_SUBMISSION', 'SCORES_EXAM_SUBMISSION'), ('TEACHING_CHARGE_APPLICATION', 'TEACHING_CHARGE_APPLICATION'), ('COURSE_ENROLLMENT', 'COURSE_ENROLLMENT')], max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='offeryearcalendar',
            unique_together={('academic_calendar', 'education_group_year')},
        ),
        migrations.AddField(
            model_name='entitycomponentyear',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entitycontaineryear',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupelementyear',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningclassyear',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningcontainer',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningunit',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningunitcomponent',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningunitcomponentclass',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningunitenrollment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
