# Generated by Django 2.2.5 on 2020-01-04 01:24

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('base', '0192_auto_20171123_0827'), ('base', '0193_auto_20171124_0907'), ('base', '0194_auto_20171124_0926'), ('base', '0195_auto_20171124_1018'), ('base', '0196_auto_20171128_1442'), ('base', '0197_auto_20171130_0823')]

    dependencies = [
        ('base', '0191_auto_20171122_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupelementyear',
            name='sessions_derogation',
            field=models.CharField(choices=[('SESSION_1', 'SESSION_1'), ('SESSION_2', 'SESSION_2'), ('SESSION_3', 'SESSION_3'), ('SESSION_1_2', 'SESSION_1_2'), ('SESSION_1_3', 'SESSION_1_3'), ('SESSION_2_3', 'SESSION_2_3'), ('SESSION_1_2_3', 'SESSION_1_2_3'), ('SESSION_UNDEFINED', 'SESSION_UNDEFINED'), ('SESSION_PARTIAL_2_3', 'SESSION_PARTIAL_2_3')], default='SESSION_UNDEFINED', max_length=65),
        ),
        migrations.AlterField(
            model_name='educationgrouporganization',
            name='diploma',
            field=models.CharField(choices=[('UNIQUE', 'UNIQUE'), ('SEPARATE', 'SEPARATE'), ('NOT_CONCERNED', 'NOT_CONCERNED')], default='NOT_CONCERNED', max_length=40),
        ),
        migrations.CreateModel(
            name='EducationGroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('TRAINING', 'TRAINING'), ('MINI_TRAINING', 'MINI_TRAINING'), ('GROUP', 'GROUP')], default='TRAINING', max_length=25)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='educationgroupyear',
            name='category',
        ),
        migrations.RemoveField(
            model_name='educationgroupyear',
            name='education_group_type',
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='education_group_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupType'),
        ),
        migrations.CreateModel(
            name='PersonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_child', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Entity')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
            ],
            options={
                'unique_together': {('person', 'entity')},
            },
        ),
        migrations.CreateModel(
            name='ProposalFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('folder_id', models.IntegerField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Entity')),
            ],
            options={
                'unique_together': {('entity', 'folder_id')},
            },
        ),
        migrations.CreateModel(
            name='ProposalLearningUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('CREATION', 'CREATION'), ('MODIFICATION', 'MODIFICATION'), ('TRANSFORMATION', 'TRANSFORMATION'), ('TRANSFORMATION_AND_MODIFICATION', 'TRANSFORMATION_AND_MODIFICATION'), ('SUPPRESSION', 'SUPPRESSION')], max_length=50)),
                ('state', models.CharField(choices=[('FACULTY', 'FACULTY'), ('CENTRAL', 'CENTRAL'), ('SUSPENDED', 'SUSPENDED'), ('ACCEPTED', 'ACCEPTED'), ('REFUSED', 'REFUSED')], max_length=50)),
                ('initial_data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ProposalFolder')),
                ('learning_unit_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnitYear')),
            ],
        ),
        migrations.AddField(
            model_name='educationgrouplanguage',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='educationgrouplanguage',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
