# Generated by Django 2.2.5 on 2020-01-04 01:24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('base', '0199_learningunitenrollment_enrollment_state'), ('base', '0200_examenrollment_deleted'), ('base', '0201_auto_20171204_1659'), ('base', '0202_auto_20171127_1302')]

    dependencies = [
        ('base', '0198_auto_20171130_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunitenrollment',
            name='enrollment_state',
            field=models.CharField(blank=True, choices=[('ENROLLED', 'ENROLLED')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='examenrollment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offerenrollment',
            name='enrollment_state',
            field=models.CharField(blank=True, choices=[('SUBSCRIBED', 'SUBSCRIBED'), ('PROVISORY', 'PROVISORY'), ('PENDING', 'PENDING'), ('TERMINATION', 'TERMINATION'), ('END_OF_CYCLE', 'END_OF_CYCLE')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='entitycomponentyear',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='entitycontaineryear',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='entityversion',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
    ]
