# Generated by Django 2.2.5 on 2020-01-04 01:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('base', '0204_remove_uuid_null'), ('base', '0205_auto_20171218_1408'), ('base', '0206_sessionexamdeadline_deliberation_date'), ('base', '0207_auto_20171220_1035')]

    dependencies = [
        ('base', '0203_populate_uuid_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='entitycomponentyear',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='entitycontaineryear',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('is_administrator', 'Is administrator'), ('is_institution_administrator', 'Is institution administrator '), ('can_edit_education_group_administrative_data', 'Can edit education group administrative data'))},
        ),
        migrations.AddField(
            model_name='sessionexamdeadline',
            name='deliberation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='acronym',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
