# Generated by Django 2.2.5 on 2020-01-04 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('base', '0209_auto_20180103_1536'), ('base', '0210_auto_20180105_1644'), ('base', '0211_auto_20180109_1436'), ('base', '0212_remove_offeryearcalendar_customized'), ('base', '0213_auto_20180111_1452'), ('base', '0214_auto_20180109_1529'), ('base', '0215_auto_20180115_1220'), ('base', '0216_auto_20180116_1026')]

    dependencies = [
        ('base', '0208_create_role_executive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeryearentity',
            name='offer_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.OfferYear'),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='reference',
            field=models.CharField(blank=True, choices=[('DELIBERATION', 'DELIBERATION'), ('DISSERTATION_SUBMISSION', 'DISSERTATION_SUBMISSION'), ('EXAM_ENROLLMENTS', 'EXAM_ENROLLMENTS'), ('SCORES_EXAM_DIFFUSION', 'SCORES_EXAM_DIFFUSION'), ('SCORES_EXAM_SUBMISSION', 'SCORES_EXAM_SUBMISSION'), ('TEACHING_CHARGE_APPLICATION', 'TEACHING_CHARGE_APPLICATION'), ('COURSE_ENROLLMENT', 'COURSE_ENROLLMENT'), ('SUMMARY_COURSE_SUBMISSION', 'SUMMARY_COURSE_SUBMISSION')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='attribution_procedure',
            field=models.CharField(blank=True, choices=[('INTERNAL_TEAM', 'INTERNAL_TEAM'), ('EXTERNAL', 'EXTERNAL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='quadrimester',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q1&2', 'Q1&2'), ('Q1|2', 'Q1|2'), ('Q3', 'Q3')], max_length=4, null=True),
        ),
        migrations.RemoveField(
            model_name='offeryearcalendar',
            name='customized',
        ),
        migrations.AlterField(
            model_name='sessionexamcalendar',
            name='academic_calendar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.AcademicCalendar'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionexamcalendar',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='learningcontainer',
            name='auto_renewal_until',
        ),
        migrations.RemoveField(
            model_name='learningcontainer',
            name='start_year',
        ),
        migrations.AddField(
            model_name='groupelementyear',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='groupelementyear',
            name='comment_english',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='groupelementyear',
            name='minor_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entitycomponentyear',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='entitycontaineryear',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='examenrollment',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='groupelementyear',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='learningclassyear',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='learningcomponentyear',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='learningcontainer',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='learningunit',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='learningunitcomponent',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='learningunitcomponentclass',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='learningunitenrollment',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
