# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-03 14:36
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0208_create_role_executive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeryearentity',
            name='offer_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.OfferYear'),
        ),
    ]
