# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0236_learningunityrae_summary_editable'),
    ]

    operations = [
        migrations.RunSQL(
            [(
             "INSERT INTO osis_common_messagetemplate (reference, subject, template, format, language) VALUES (%s, %s, %s, %s, %s);",
             ['learning_unit_year_proposal_canceled_html',
              'Annulation d\u0027une mise en proposition',
              '{% autoescape off %}\r\n<p>Bonjour {{ first_name }} {{ last_name }},<br />\r\nCeci est un message automatique g\u00e9n\u00e9r\u00e9 par le serveur OSIS – Merci de ne pas y r\u00e9pondre.<br />\r\n<br />\r\nVous avez demandé l\u0027annulation de la mise en proposition de :<br />\r\n<ul>{% for learning_unit in learning_units %}<li>{{ learning_unit.acronym }}pour l\u0027année {{ learning_unit.academic_year }}</li>{% endfor %}</ul>\r\n<br />\r\nCordialement,<br />\r\nOsis UCLouvain<br /></p>\r\n{% endautoescape %}',
              'HTML',
              'fr-be'])],
        ),
        migrations.RunSQL(
            [(
             "INSERT INTO osis_common_messagetemplate (reference, subject, template, format, language) VALUES (%s, %s, %s, %s, %s);",
             ['learning_unit_year_proposal_canceled_txt',
              'Annulation d\u0027une mise en proposition ',
              '<p>Bonjour {{ first_name }} {{ last_name }},<br />\r\nCeci est un message automatique g\u00e9n\u00e9r\u00e9 par le serveur OSIS – Merci de ne pas y r\u00e9pondre.<br />\r\n<br />\r\nVous avez demandé l\u0027annulation de la mise en proposition :<br />\r\n<ul>{% for learning_unit in learning_units %}<li>{{ learning_unit.acronym }}pour l\u0027année {{ learning_unit.academic_year }} </li> {% endfor %}</ul>\r\n<br />\r\nCordialement,<br />\r\nOsis UCLouvain<br /></p>\r\n',
              'PLAIN',
              'fr-be'])],
        ),
        migrations.RunSQL(
            [(
             "INSERT INTO osis_common_messagetemplate (reference, subject, template, format, language) VALUES (%s, %s, %s, %s, %s);",
             ['learning_unit_year_proposal_canceled_html',
              'Cancellation of a proposal',
              '{% autoescape off %}\r\n<p>Hello {{ first_name }} {{ last_name }},<br />\r\nThis is an automatic message generated by the OSIS server – Please do not reply to this message.<br />\r\n<br />\r\nYou asked for the cancellation of the putting in proposal of :<br />\r\n<ul>{% for learning_unit in learning_units %}<li>{{ learning_unit.acronym }}for the year {{ learning_unit.academic_year }} </li> {% endfor %}</ul>\r\n<br />\r\nRegards,<br />\r\nOsis UCLouvain<br /></p>\r\n{% endautoescape off %}',
              'HTML',
              'en'])],
        ),
        migrations.RunSQL(
            [(
             "INSERT INTO osis_common_messagetemplate (reference, subject, template, format, language) VALUES (%s, %s, %s, %s, %s);",
             ['learning_unit_year_proposal_canceled_txt',
              'Cancellation of a proposal',
              '<p>Hello {{ first_name }} {{ last_name }},<br />\r\nThis is an automatic message generated by the OSIS server – Please do not reply to this message.<br />\r\n<br />\r\nYou asked for the cancellation of the putting in proposal of  :<br />\r\n<ul>{% for learning_unit in learning_units %}<li>{{ learning_unit.acronym }}for the year {{ learning_unit.academic_year }}</li>{% endfor %}</ul>\r\n<br />\r\nRegards,<br />\r\nOsis UCLouvain<br /></p>\r\n',
              'PLAIN',
              'en'])],
        ),
    ]
