# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-19 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0288_auto_20180618_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bibliography',
            new_name='TeachingMaterial',
        ),
    ]
