# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-19 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0289_auto_20180619_1435'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bibliography',
            new_name='TeachingMaterial',
        ),
        migrations.AlterModelOptions(
            name='teachingmaterial',
            options={},
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='bibliography',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
