# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-21 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0293_auto_20180621_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bibliography',
            new_name='TeachingMaterial',
        ),
        migrations.AlterModelOptions(
            name='teachingmaterial',
            options={},
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='bibliography',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='bibliography'),
        ),
    ]
