# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 09:15
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0303_auto_20180705_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeryeardomain',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.Domain'),
        ),
    ]
