# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-26 16:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0377_auto_20181024_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupyear',
            name='credits',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='credits'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='max_constraint',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='maximum constraint'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='min_constraint',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='minimum constraint'),
        ),
    ]
