# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-29 11:25
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0378_auto_20181026_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallearningunityear',
            name='external_acronym',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='external_code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='externallearningunityear',
            name='learning_unit_year',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnitYear', verbose_name='learning unit year'),
        ),
        migrations.AlterField(
            model_name='externallearningunityear',
            name='requesting_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Entity', verbose_name='requesting_entity'),
        ),
        migrations.AlterField(
            model_name='externallearningunityear',
            name='url',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='url of the learning unit'),
            preserve_default=False,
        ),
    ]
