# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-14 12:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0388_auto_20181109_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenrollment',
            name='score_draft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0, message='Les notes doivent être comprises entre 0 et 20'), django.core.validators.MaxValueValidator(20, message='Les notes doivent être comprises entre 0 et 20')]),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='score_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0, message='Les notes doivent être comprises entre 0 et 20'), django.core.validators.MaxValueValidator(20, message='Les notes doivent être comprises entre 0 et 20')]),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='score_reencoded',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0, message='Les notes doivent être comprises entre 0 et 20'), django.core.validators.MaxValueValidator(20, message='Les notes doivent être comprises entre 0 et 20')]),
        ),
    ]
