# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-21 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0398_remove_prerequisite_prerequisite'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunityear',
            name='learning_component_years',
            field=models.ManyToManyField(through='base.LearningUnitComponent', to='base.LearningComponentYear', verbose_name='Components'),
        ),
    ]
