# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-11 14:27
from __future__ import unicode_literals

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0412_auto_20181211_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('ares_study', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='ARES study code')),
                ('ares_graca', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='ARES-GRACA')),
                ('ares_ability', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='ARES ability')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='educationgroupyear',
            name='ARES_GRACA',
        ),
        migrations.RemoveField(
            model_name='educationgroupyear',
            name='ARES_ability',
        ),
        migrations.RemoveField(
            model_name='educationgroupyear',
            name='ARES_study',
        ),
        migrations.AddField(
            model_name='hops',
            name='education_group_year',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupYear'),
        ),
    ]
