# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-11 17:00
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0413_hops'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroupyear',
            name='publication_contact_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Entity', verbose_name='Publication contact entity'),
        ),
    ]
