# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-14 07:25
from __future__ import unicode_literals

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0421_auto_20190107_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hops',
            name='ares_ability',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='ARES ability'),
        ),
        migrations.AlterField(
            model_name='hops',
            name='ares_graca',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='ARES-GRACA'),
        ),
        migrations.AlterField(
            model_name='hops',
            name='ares_study',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='ARES study code'),
            preserve_default=False,
        ),
    ]
