# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-29 14:08
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0426_educationgroupyear_linked_with_epc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externallearningunityear',
            name='date',
        ),
        migrations.AddField(
            model_name='externallearningunityear',
            name='co_graduation',
            field=models.BooleanField(default=False, verbose_name='Co-graduation'),
        ),
        migrations.AddField(
            model_name='externallearningunityear',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='externallearningunityear',
            name='mobility',
            field=models.BooleanField(default=False, verbose_name='Mobility'),
        ),
        migrations.AlterField(
            model_name='externallearningunityear',
            name='external_acronym',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='External code'),
        ),
        migrations.AlterField(
            model_name='externallearningunityear',
            name='external_credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500)], verbose_name='Local credits'),
        ),
        migrations.AlterField(
            model_name='externallearningunityear',
            name='requesting_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Entity', verbose_name='Requesting entity'),
        ),
        migrations.AlterField(
            model_name='externallearningunityear',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL of the learning unit'),
        ),
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='container_type',
            field=models.CharField(choices=[('COURSE', 'Course'), ('INTERNSHIP', 'Internship'), ('DISSERTATION', 'Dissertation'), ('OTHER_COLLECTIVE', 'Other collective'), ('OTHER_INDIVIDUAL', 'Other individual'), ('MASTER_THESIS', 'Master thesis'), ('EXTERNAL', 'External')], db_index=True, max_length=20, verbose_name='Type'),
        ),
    ]
