# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-01 15:20
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0427_auto_20190129_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissioncondition',
            options={'permissions': (('change_commonadmissioncondition', 'Can change common admission condition'),)},
        ),
        migrations.AlterModelOptions(
            name='educationgroup',
            options={'permissions': (('can_access_education_group', 'Can access education_group'), ('change_commonpedagogyinformation', 'Can change common pedagogy information'), ('change_pedagogyinformation', 'Can change pedagogy information'))},
        ),
        migrations.AlterField(
            model_name='externallearningunityear',
            name='requesting_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Entity', verbose_name='Requesting entity'),
        ),
    ]
