# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-11 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0443_auto_20190410_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingmaterial',
            name='mandatory',
            field=models.BooleanField(verbose_name='Is this teaching material mandatory?'),
        ),
    ]
