# -*- coding: utf-8 -*-
# Generated by Laurent Spitaels on 2019-05-27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0456_auto_20190515_1555'),
    ]

    operations = [
        migrations.RunSQL(
            [("UPDATE osis_common_messagetemplate SET template=%s WHERE reference=%s AND format=%s AND language=%s;",
              ['''{% autoescape off %}
                <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
                <p>Bonjour,</p>
                
                <p>Ceci est un message automatique g&eacute;n&eacute;r&eacute; par le serveur OSIS &ndash; Merci de ne pas y r&eacute;pondre.</p>
                
                <p>Lancement de la proc&eacute;dure annuelle de copie des organisations de formation pour l&#39;ann&eacute;e acad&eacute;mique {{ end_academic_year }}.</p>
                
                <p><strong>{{ egys_postponed }} OF copi&eacute;es de {{ academic_year }} en {{ end_academic_year }}.</strong></p>
                
                {% if egys_postponed %}
                <div class="w3-responsive">
                <table class="w3-table w3-striped w3-hoverable">
                    <thead>
                        <tr>
                            <th>Sigle</th>
                            <th>Intitul&eacute;</th>
                            <th>Ann&eacute;e de report</th>
                        </tr>
                    </thead>
                
                    <tbody>
                    {% for egy in egys_postponed_qs %}
                        {% ifchanged  egy.verbose_type%}
                        <tr>
                            <th colspan="3">{{ egy.verbose_type }}</th>
                        </tr>
                        {% endifchanged %}
                        <tr>
                            <td>{{ egy.verbose }}</td>
                            <td>{{ egy.complete_title }}</td>
                            <td>{{ egy.academic_year }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                </div>
                {% endif %}
                
                <p><strong>{{ egys_ending_this_year }} OF avec une fin d&#39;enseignement en {{ academic_year }}.</strong></p>
                
                {% if egys_ending_this_year %}
                <div class="w3-responsive">
                <table class="w3-table w3-striped w3-hoverable">
                    <thead>
                        <tr>
                            <th>Sigle</th>
                            <th>Intitul&eacute;</th>
                        </tr>
                    </thead>
                
                    <tbody>
                    {% for eg in egys_ending_this_year_qs %}
                        {% with egy=eg.educationgroupyear_set.last %}
                        {% ifchanged  egy.verbose_type%}
                        <tr>
                            <th colspan="2">{{ egy.verbose_type }}</th>
                        </tr>
                        {% endifchanged %}
                        <tr>
                            <td>{{ egy.verbose }}</td>
                            <td>{{ egy.complete_title }}</td>
                        </tr>
                        {% endwith %}
                    {% endfor %}
                    </tbody>
                </table>
                </div>
                {% endif %}
                
                <p><strong>{{ egys_already_existing }} OF existant pr&eacute;alablement en {{ end_academic_year }}.</strong></p>
                
                {% if egys_already_existing %}
                <div class="w3-responsive">
                <table class="w3-table w3-striped w3-hoverable">
                    <thead>
                        <tr>
                            <th>Sigle</th>
                            <th>Intitul&eacute;</th>
                        </tr>
                    </thead>
                
                    <tbody>
                    {% for eg in egys_already_existing_qs %}
                        {% with egy=eg.educationgroupyear_set.last %}
                        {% ifchanged  egy.verbose_type%}
                        <tr>
                            <th colspan="2">{{ egy.verbose_type }}</th>
                        </tr>
                        {% endifchanged %}
                        <tr>
                            <td>{{ egy.verbose }}</td>
                            <td>{{ egy.complete_title }}</td>
                        </tr>
                        {% endwith %}
                    {% endfor %}
                    </tbody>
                </table>
                </div>
                {% endif %}
                {% if egys_with_errors %}
                
                    <p><strong>Les organisations de formation suivantes n&#39;ont pas &eacute;t&eacute; recopi&eacute;es :</strong></p>
                
                    <div class="w3-responsive">
                    <table class="w3-table w3-striped w3-hoverable">                
                        <tbody>
                        {% for eg in egys_with_errors %}
                        {% with egy=eg.educationgroupyear_set.last %}
                            <tr>
                                <td>{{ egy.verbose }}</td>
                                <td>{{ egy.complete_title }}</td>
                                <td>{{ egy.academic_year }}</td>
                            </tr>
                        {% endwith %}
                        {% endfor %}
                        </tbody>
                    </table>
                    </div>
                {% endif %}
                <p>Cordialement, Osis UCLouvain</p>
                {% endautoescape %}''',
               'egy_after_auto_postponement_html',
               'HTML',
               'fr-be'])],
        ),
        migrations.RunSQL(
            [("UPDATE osis_common_messagetemplate SET template=%s WHERE reference=%s AND format=%s AND language=%s;",
              ['''<p>Bonjour,</p>
                
                <p>Ceci est un message automatique g&eacute;n&eacute;r&eacute; par le serveur OSIS &ndash; Merci de ne pas y r&eacute;pondre.</p>
                
                <p>Lancement de la proc&eacute;dure annuelle de copie des organisations de formation pour l&#39;ann&eacute;e acad&eacute;mique {{ end_academic_year }}.</p>
                
                <p><strong>{{ egys_postponed }} OF copi&eacute;es de {{ academic_year }} en {{ end_academic_year }}.</strong></p>
                
                {% if egys_postponed %}
                <strong>Sigle - Intitul&eacute; - Ann&eacute;e de report</strong><br/>
                    {% for egy in egys_postponed_qs %}
                        {% ifchanged  egy.verbose_type%}
                            <strong>{{ egy.verbose_type }}</strong><br/>
                        {% endifchanged %}
                        {{ egy.verbose }} - {{ egy.complete_title }} - {{ egy.academic_year }}<br/>
                    {% endfor %}
                {% endif %}
                
                <p><strong>{{ egys_ending_this_year }} OF avec une fin d&#39;enseignement en {{ academic_year }}.</strong></p>
                
                {% if egys_ending_this_year %}
                <strong>Sigle - Intitul&eacute;</strong><br/>
                    {% for eg in egys_ending_this_year_qs %}
                        {% with egy=eg.educationgroupyear_set.last %}
                        {% ifchanged  egy.verbose_type%}
                            <strong>{{ egy.verbose_type }}</strong><br/>
                        {% endifchanged %}
                        {{ egy.verbose }} - {{ egy.complete_title }}<br/>
                        {% endwith %}
                    {% endfor %}
                {% endif %}
                
                <p><strong>{{ egys_already_existing }} OF existant pr&eacute;alablement en {{ end_academic_year }}.</strong></p>
                
                {% if egys_already_existing %}
                <strong>Sigle - Intitul&eacute;</strong><br/>
                    {% for eg in egys_already_existing_qs %}
                        {% with egy=eg.educationgroupyear_set.last %}
                        {% ifchanged  egy.verbose_type%}
                            <strong>{{ egy.verbose_type }}</strong><br/>
                        {% endifchanged %}
                        {{ egy.verbose }} - {{ egy.complete_title }}<br/>
                        {% endwith %}
                    {% endfor %}
                {% endif %}
                {% if egys_with_errors %}
                
                    <p><strong>Les organisations de formation suivantes n&#39;ont pas &eacute;t&eacute; recopi&eacute;es :</strong></p>
                
                    {% for eg in egys_with_errors %}
                        {% with egy=eg.educationgroupyear_set.last %}
                        {{ egy.verbose }} - {{ egy.complete_title }}<br/>
                    {% endwith %}
                    {% endfor %}
                {% endif %}
                <p>Cordialement, Osis UCLouvain</p>
                ''',
               'egy_after_auto_postponement_txt',
               'PLAIN',
               'fr-be'])],
        ),
        migrations.RunSQL(
            [("UPDATE osis_common_messagetemplate SET template=%s WHERE reference=%s AND format=%s AND language=%s;",
              ['''{% autoescape off %}
                <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
                <p>Hello,</p>
                
                <p>This is an automatic message generated by the OSIS server &ndash; Please do not reply to this message.</p>
                
                <p>Report of the annual procedure of copy of the education groups for the academic year {{ end_academic_year }}.</p>
                
                <p><strong>{{ egys_postponed }} EG copied from {{ academic_year }} to {{ end_academic_year }}.</strong></p>
                
                {% if egys_postponed %}
                <div class="w3-responsive">
                <table class="w3-table w3-striped w3-hoverable">
                    <thead>
                        <tr>
                            <th>Acronym</th>
                            <th>Title</th>
                            <th>Year of postponement</th>
                        </tr>
                    </thead>
                
                    <tbody>
                    {% for egy in egys_postponed_qs %}
                        {% ifchanged  egy.verbose_type%}
                        <tr>
                            <th colspan="3">{{ egy.verbose_type }}</th>
                        </tr>
                        {% endifchanged %}
                        <tr>
                            <td>{{ egy.verbose }}</td>
                            <td>{{ egy.complete_title }}</td>
                            <td>{{ egy.academic_year }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                </div>
                {% endif %}
                
                <p><strong>{{ egys_ending_this_year }} EG ending in {{ academic_year }}.</strong></p>
                
                {% if egys_ending_this_year %}
                <div class="w3-responsive">
                <table class="w3-table w3-striped w3-hoverable">
                    <thead>
                        <tr>
                            <th>Acronym</th>
                            <th>Title</th>
                        </tr>
                    </thead>
                
                    <tbody>
                    {% for eg in egys_ending_this_year_qs %}
                        {% with egy=eg.educationgroupyear_set.last %}
                        {% ifchanged  egy.verbose_type%}
                        <tr>
                            <th colspan="2">{{ egy.verbose_type }}</th>
                        </tr>
                        {% endifchanged %}
                        <tr>
                            <td>{{ egy.verbose }}</td>
                            <td>{{ egy.complete_title }} - {{ egy.verbose_type }}</td>
                        </tr>
                        {% endwith %}
                    {% endfor %}
                    </tbody>
                </table>
                </div>
                {% endif %}
                
                <p><strong>{{ egys_already_existing }} EG already existing in {{ end_academic_year }}.</strong></p>
                
                {% if egys_already_existing %}
                <div class="w3-responsive">
                <table class="w3-table w3-striped w3-hoverable">
                    <thead>
                        <tr>
                            <th>Acronym</th>
                            <th>Title</th>
                        </tr>
                    </thead>
                
                    <tbody>
                    {% for eg in egys_already_existing_qs %}
                        {% with egy=eg.educationgroupyear_set.last %}
                        {% ifchanged  egy.verbose_type%}
                        <tr>
                            <th colspan="2">{{ egy.verbose_type }}</th>
                        </tr>
                        {% endifchanged %}
                        <tr>
                            <td>{{ egy.verbose }}</td>
                            <td>{{ egy.complete_title }} - {{ egy.verbose_type }}</td>
                        </tr>
                        {% endwith %}
                    {% endfor %}
                    </tbody>
                </table>
                </div>
                {% endif %}
                {% if egys_with_errors %}
                
                    <p><strong>Errors occured with the following education groups :</strong></p>
                
                    <div class="w3-responsive">
                    <table class="w3-table w3-striped w3-hoverable">
                        <thead>
                            <tr>
                                <th>Acronym</th>
                                <th>Title</th>
                            </tr>
                        </thead>
                
                        <tbody>
                        {% for eg in egys_with_errors %}
                        {% with egy=eg.educationgroupyear_set.last %}
                            <tr>
                                <td>{{ egy.verbose }}</td>
                                <td>{{ egy.complete_title }} - {{ egy.verbose_type }}</td>
                            </tr>
                        {% endwith %}
                        {% endfor %}
                        </tbody>
                    </table>
                    </div>
                {% endif %}
                <p>Regards, Osis UCLouvain</p>
                {% endautoescape %}''',
               'egy_after_auto_postponement_html',
               'HTML',
               'en'])],
        ),
        migrations.RunSQL(
            [("UPDATE osis_common_messagetemplate SET template=%s WHERE reference=%s AND format=%s AND language=%s;",
              ['''<p>Hello,</p>
                
                <p>This is an automatic message generated by the OSIS server &ndash; Please do not reply to this message.</p>
                
                <p>Report of the annual procedure of copy of the education groups for the academic year {{ end_academic_year }}.</p>
                
                <p><strong>{{ egys_postponed }} EG copied from {{ academic_year }} to {{ end_academic_year }}.</strong></p>
                
                {% if egys_postponed %}
                <strong>Acronym - Title - Year of postponement</strong><br/>
                    {% for egy in egys_postponed_qs %}
                        {% ifchanged  egy.verbose_type%}
                            <strong>{{ egy.verbose_type }}</strong><br/>
                        {% endifchanged %}
                        {{ egy.verbose }} - {{ egy.complete_title }} - {{ egy.academic_year }}<br/>
                    {% endfor %}
                {% endif %}
                
                <p><strong>{{ egys_ending_this_year }} EG ending in {{ academic_year }}.</strong></p>
                
                {% if egys_ending_this_year %}
                <strong>Acronym - Title</strong><br/>
                    {% for eg in egys_ending_this_year_qs %}
                        {% with egy=eg.educationgroupyear_set.last %}
                        {% ifchanged  egy.verbose_type%}
                            <strong>{{ egy.verbose_type }}</strong><br/>
                        {% endifchanged %}
                        {{ egy.verbose }} - {{ egy.complete_title }}<br/>
                        {% endwith %}
                    {% endfor %}
                {% endif %}
                
                <p><strong>{{ egys_already_existing }} EG already existing in {{ end_academic_year }}.</strong></p>
                
                {% if egys_already_existing %}
                <strong>Acronym - Title</strong><br/>
                    {% for eg in egys_already_existing_qs %}
                        {% with egy=eg.educationgroupyear_set.last %}
                        {% ifchanged  egy.verbose_type%}
                            <strong>{{ egy.verbose_type }}</strong><br/>
                        {% endifchanged %}
                        {{ egy.verbose }} - {{ egy.complete_title }}<br/>
                        {% endwith %}
                    {% endfor %}
                {% endif %}
                {% if egys_with_errors %}
                
                    <p><strong>Errors occured with the following education groups :</strong></p>
                
                    <strong>Acronym - Title</strong><br/>
                    {% for eg in egys_with_errors %}
                        {% with egy=eg.educationgroupyear_set.last %}
                        {{ egy.verbose }} - {{ egy.complete_title }}<br/>
                    {% endwith %}
                    {% endfor %}
                {% endif %}
                
                <p>Regards, Osis UCLouvain</p>
                ''',
               'egy_after_auto_postponement_txt',
               'PLAIN',
               'en'])],
        ),
    ]
