# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-06 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0466_auto_20190730_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroup',
            name='new_end_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='end_years', to='base.AcademicYear', verbose_name='Last year of organization'),
        ),
        migrations.AddField(
            model_name='educationgroup',
            name='new_start_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='start_years', to='base.AcademicYear', verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='educationgroup',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Last year of organization'),
        ),
    ]
