# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-19 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0467_create_permission_person_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningunityear',
            options={'ordering': ('academic_year', 'acronym'), 'permissions': (('can_receive_emails_about_automatic_postponement', 'Can receive emails about automatic postponement'),), 'verbose_name': 'Learning unit year'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('is_administrator', 'Is administrator'), ('is_institution_administrator', 'Is institution administrator '), ('can_edit_education_group_administrative_data', 'Can edit education group administrative data'), ('can_manage_charge_repartition', 'Can manage charge repartition'), ('can_manage_attribution', 'Can manage attribution'))},
        ),
        migrations.AlterModelOptions(
            name='programmanager',
            options={'permissions': (('view_programmanager', 'Can view program manager'),)},
        ),
    ]
