# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-29 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0472_auto_20190807_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunit',
            name='new_end_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ue_end_years', to='base.AcademicYear', verbose_name='Last year of organization'),
        ),
        migrations.AddField(
            model_name='learningunit',
            name='new_start_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ue_start_years', to='base.AcademicYear', verbose_name='Start'),
        ),
    ]
