# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-10 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0472_auto_20190807_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmanager',
            options={'permissions': (('view_programmanager', 'Can view program manager'),)},
        ),
    ]
