# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-06 09:59
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0473_auto_20190910_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccalendar',
            name='data_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_academic_calendar_data', to='base.AcademicYear'),
        ),
    ]
