# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-29 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0477_auto_20190829_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningunit',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='learningunit',
            name='start_year',
        ),
    ]
