# Generated by Django 2.2.5 on 2019-11-06 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0480_auto_20191025_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoresEncoding',
        ),
        migrations.AlterField(
            model_name='educationgroup',
            name='start_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='start_years', to='base.AcademicYear', verbose_name='Start academic year'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='end_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_unit_end_years', to='base.AcademicYear', verbose_name='Last year of organization'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='start_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_unit_start_years', to='base.AcademicYear', verbose_name='Start academic year'),
        ),
    ]
