# Generated by Django 2.2.5 on 2019-12-11 14:52

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0487_auto_20191206_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('-is_current_partner', 'name'), 'permissions': (('can_access_organization', 'Can access organization'),)},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('person__last_name', 'person__first_name'), 'permissions': (('can_access_student', 'Can access student'),)},
        ),
        migrations.AlterField(
            model_name='educationgroup',
            name='start_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='start_years', to='base.AcademicYear', verbose_name='Start academic year'),
        ),
        migrations.AlterField(
            model_name='proposallearningunit',
            name='initial_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
