# Generated by Django 2.2.5 on 2019-12-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0488_auto_20191211_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationgroup',
            options={'permissions': (('can_access_education_group', 'Can access education_group'), ('change_commonpedagogyinformation', 'Can change common pedagogy information'), ('change_pedagogyinformation', 'Can change pedagogy information'), ('change_educationgroupcontent', 'Can change education group content')), 'verbose_name': 'Education group'},
        ),
    ]
