# Generated by Django 2.2.5 on 2020-01-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0490_remove_learningunit_existing_proposal_in_epc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationgroup',
            options={'permissions': (('can_access_education_group', 'Can access education_group'), ('change_commonpedagogyinformation', 'Can change common pedagogy information'), ('change_pedagogyinformation', 'Can change pedagogy information'), ('change_educationgroupcontent', 'Can change education group content')), 'verbose_name': 'Education group'},
        ),
    ]
