# Generated by Django 2.2.5 on 2020-01-13 13:16

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0491_auto_20200107_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerenrollment',
            name='enrollment_state',
            field=models.CharField(blank=True, choices=[('SUBSCRIBED', 'Subscribed'), ('PROVISORY', 'Provisory'), ('PENDING', 'Pending'), ('TERMINATION', 'Termination'), ('END_OF_CYCLE', 'End of cycle')], db_index=True, max_length=15, null=True),
        ),
    ]
