# Generated by Django 2.2.5 on 2020-01-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_auto_20190308_1450'),
        ('base', '0495_learningachievement_consistency_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='learningachievement',
            unique_together={('consistency_id', 'learning_unit_year', 'language')},
        ),
    ]
