# Generated by Django 2.2.5 on 2020-01-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0002_auto_20200124_2055'),
        ('base', '0497_auto_20200108_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningClassYear',
        ),
    ]
