# Generated by Django 2.2.5 on 2020-02-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0503_auto_20200131_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupyear',
            name='diploma_printing_title',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Diploma title'),
        ),
    ]
