# Generated by Django 2.2.5 on 2020-03-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0506_remove_prerequisites_whithout_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunit',
            name='faculty_remark',
            field=models.TextField(blank=True, null=True, verbose_name='Faculty remark (unpublished)'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='other_remark',
            field=models.TextField(blank=True, null=True, verbose_name='Other remark (intended for publication)'),
        ),
    ]
