# Generated by Django 2.2.10 on 2020-06-19 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0508_auto_20200325_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSpecificProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(
                    choices=[('NOT_DEFINED', 'Not defined'), ('DISABILITY', 'Disability'), ('SPORT', 'Sport'),
                             ('ARTIST', 'Artist'), ('ENTREPRENEUR', 'Entrepreneur'),
                             ('ARRANGEMENT_JURY', 'Arrangement Jury')], max_length=20)),
                ('subtype_disability', models.CharField(blank=True,
                                                        choices=[('REDUCED_MOBILITY', 'Person with reduced mobility'),
                                                                 ('OTHER_DISABILITY', 'Other disability')],
                                                        max_length=20, verbose_name='Sub type Disability')),
                ('subtype_sport', models.CharField(blank=True,
                                                   choices=[('PROMISING_ATHLETE_HL', 'High Level Promising athlete'),
                                                            ('PROMISING_ATHLETE', 'Promising athlete')], max_length=20,
                                                   verbose_name='Sub type Sport')),
                ('arrangement_additional_time',
                 models.BooleanField(default=False, verbose_name='Arrangement additional time')),
                ('arrangement_appropriate_copy',
                 models.BooleanField(default=False, verbose_name='Arrangement appropriate copy')),
                ('arrangement_other', models.BooleanField(default=False, verbose_name='Arrangement other')),
                ('arrangement_specific_locale',
                 models.BooleanField(default=False, verbose_name='Arrangement specific locale')),
                ('guide',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Person',
                                   verbose_name='Guide')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='base.Student')),
            ],
            options={
                'ordering': ('student', 'guide__last_name', 'guide__first_name'),
            },
        ),
    ]
