# Generated by Django 2.2.10 on 2020-04-16 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0004_auto_20200323_1055'),
        ('base', '0510_auto_20200408_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupelementyear',
            name='child_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_elements', to='program_management.Element'),
        ),
        migrations.AddField(
            model_name='groupelementyear',
            name='parent_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_elements', to='program_management.Element'),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='education_group_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program_management.EducationGroupVersion'),
        ),
    ]
