# Generated by Django 2.2.10 on 2020-04-16 15:18

import base.models.entity_version
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0511_auto_20200416_1234'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entityversion',
            managers=[
                ('objects', base.models.entity_version.EntityVersionManager()),
            ],
        ),
    ]
