# Generated by Django 2.2.10 on 2020-04-15 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0004_auto_20200323_1055'),
        ('base', '0511_element_fk_to_group_element_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequisite',
            name='education_group_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program_management.EducationGroupVersion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='partial_title',
            field=models.CharField(blank=True, default='', max_length=240, null=True, verbose_name='Partial title in French'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='partial_title_english',
            field=models.CharField(blank=True, default='', max_length=240, null=True, verbose_name='Partial title in English'),
        ),
    ]
