# Generated by Django 2.2.10 on 2020-04-24 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0512_cte_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisite',
            name='education_group_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupYear'),
        ),
    ]
