# Generated by Django 2.2.10 on 2020-05-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0514_auto_20200513_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationgroup',
            options={'permissions': (('add_training', 'Can add training'), ('add_minitraining', 'Can add mini-training'), ('add_group', 'Can add group'), ('delete_training', 'Can delete training'), ('delete_minitraining', 'Can delete mini-training'), ('delete_group', 'Can delete group'), ('change_commonpedagogyinformation', 'Can change common pedagogy information'), ('change_pedagogyinformation', 'Can change pedagogy information'), ('change_link_data', 'Can change link data')), 'verbose_name': 'Education group'},
        ),
    ]
