# Generated by Django 2.2.10 on 2020-06-11 08:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_domainisced_is_ares'),
        ('base', '0516_auto_20200602_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityVersionAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('street_number', models.CharField(blank=True, max_length=12)),
                ('postal_code', models.PositiveIntegerField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('is_main', models.BooleanField(default=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.Country')),
                ('entity_version_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.EntityVersion')),
            ],
        ),
    ]
