# Generated by Django 2.2.13 on 2020-06-23 14:46
import django.db.models.expressions
from django.db import migrations, models


def forward(apps, schema_editor):
    Organization = apps.get_model('base', 'Organization')
    Organization.objects.filter(type__in=['', 'UNKNOWN']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0519_studentspecificprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='website',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_current_partner',
        ),
        migrations.RunPython(forward, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('MAIN', 'Main'),
                    ('ACADEMIC_PARTNER', 'Academic partner'),
                    ('EMBASSY', 'Embassy'),
                    ('RESEARCH_CENTER', 'Research center'),
                    ('ENTERPRISE', 'Enterprise'), ('HOSPITAL', 'Hospital'),
                    ('NGO', 'Non-governmental organization'),
                ],
                default='',
                max_length=30,
            ),
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={
                'ordering': (
                    django.db.models.expressions.OrderBy(
                        django.db.models.expressions.F('is_current_partner'),
                        descending=True
                    ),
                    'name'
                ),
                'permissions': (
                    ('can_access_organization', 'Can access organization'),
                )
            },
        ),
    ]
