# Generated by Django 2.2.10 on 2020-06-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0519_studentspecificprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityversionaddress',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='entityversionaddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='entityversionaddress',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
