# Generated by Django 2.2.13 on 2020-06-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0520_update_entityversionaddress'),
        ('base', '0520_organization_types'),
    ]

    operations = [
    ]
