# Generated by Django 2.2.13 on 2020-07-02 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0521_merge_20200629_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='external_id',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
