# Generated by Django 2.2.13 on 2020-07-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0522_entity_external_id_nullable'),
        ('base', '0522_auto_20200703_1051'),
    ]

    operations = [
    ]
