# Generated by Django 2.2.13 on 2020-07-29 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0524_entityversionaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupyear',
            name='co_graduation_coefficient',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Co-graduation total coefficient'),
        ),
    ]
