# Generated by Django 2.2.13 on 2020-07-30 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('program_management', '0007_auto_20200424_1513'),
        ('base', '0525_add_more_decimal_co_graduation_coeff'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupelementyear',
            unique_together={('parent_element', 'child_element'), ('parent', 'child_branch'), ('parent', 'child_leaf')},
        ),
    ]
