# Generated by Django 2.2.13 on 2020-07-30 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0526_unique_together_groupelementyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupelementyear',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='base.EducationGroupYear'),
        ),
    ]
