# Generated by Django 2.2.13 on 2020-07-30 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('program_management', '0007_auto_20200424_1513'),
        ('base', '0527_auto_20200730_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisite',
            name='education_group_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='base.EducationGroupYear'),
        ),
        migrations.AlterUniqueTogether(
            name='prerequisite',
            unique_together={('learning_unit_year', 'education_group_version')},
        ),
    ]
