# Generated by Django 2.2.13 on 2020-09-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0008_auto_20200826_0835'),
        ('base', '0530_auto_20200818_0805'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupelementyear',
            name='child_branch_xor_child_leaf',
        ),
        migrations.AlterUniqueTogether(
            name='groupelementyear',
            unique_together={('parent_element', 'child_element')},
        ),
        migrations.RemoveField(
            model_name='groupelementyear',
            name='child_branch',
        ),
        migrations.RemoveField(
            model_name='groupelementyear',
            name='child_leaf',
        ),
        migrations.RemoveField(
            model_name='groupelementyear',
            name='parent',
        ),
    ]
