# Generated by Django 2.2.13 on 2020-09-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0532_auto_20200903_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationgroupyear',
            name='main_teaching_campus',
        ),
    ]
