# Generated by Django 2.2.13 on 2020-09-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0536_studentspecificprofile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunityear',
            name='professional_integration',
            field=models.BooleanField(default=False, verbose_name='Professional integration'),
        ),
    ]
