# Generated by Django 2.2.13 on 2020-10-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0537_auto_20200923_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunityear',
            name='periodicity',
            field=models.CharField(choices=[('ANNUAL', 'Annual'), ('BIENNIAL_EVEN', 'Biennial even'),
                                            ('BIENNIAL_ODD', 'Biennial odd')],
                                   default='ANNUAL', max_length=20, verbose_name='Periodicity'),
        ),
    ]
