# Generated by Django 3.1.1 on 2020-10-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0538_auto_20201005_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmanager',
            options={'verbose_name': 'Program manager', 'verbose_name_plural': 'Program managers'},
        ),
    ]
