# Generated by Django 2.2.13 on 2020-10-29 15:50

from django.db import migrations
from django.db.models import Q

from base.models.enums import organization_type


def forward(apps, schema_editor):
    # Rename bad entry on city
    EntityVersionAddress = apps.get_model('base', 'EntityVersionAddress')
    EntityVersionAddress.objects.filter(city="LEUVEN").update(city="Leuven")

    # Create default campus for each organization in order to see all external organization in
    # external learning unit year ("Insitution" field)
    Organization = apps.get_model('base', 'Organization')
    Campus = apps.get_model('base', 'Campus')

    organizations_without_campus = Organization.objects.filter(campus__isnull=True).order_by('name')
    for organization in organizations_without_campus:
        Campus.objects.create(name='', organization=organization)

    # Set all campus name to blank value in order to don't confuse with organization name on usage
    Campus.objects.filter(~Q(organization__type=organization_type.MAIN)).update(name='')


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0541_auto_20201019_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationAddress',
        ),
        migrations.RunPython(forward, migrations.RunPython.noop)
    ]
