# Generated by Django 3.1.1 on 2020-10-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0543_auto_20201120_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={
                'permissions': (
                    ('is_administrator', 'Is administrator'),
                    ('is_institution_administrator', 'Is institution administrator '),
                    ('can_edit_education_group_administrative_data', 'Can edit education group administrative data'),
                    ('can_add_charge_repartition', 'Can add charge repartition'),
                    ('can_change_attribution', 'Can change attribution'),
                    ('can_read_persons_roles', 'Can read persons roles')
                )
            },
        ),
    ]
