# Generated by Django 2.2.13 on 2020-12-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0545_auto_20201126_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupyear',
            name='decree_category',
            field=models.CharField(
                blank=True,
                choices=[
                    ('FCONT', 'FCONT - Formation continue (non académique)'),
                    ('BAC', 'BAC - Bachelier'),
                    ('MA1', 'MA1 - Master en 60 crédits'),
                    ('MA2X', 'MA2X - Master en 120 crédits'),
                    ('MA2D', 'MA2D - Master en 120 crédits à finalité didactique'),
                    ('MA2S', 'MA2S - Master en 120 crédits à finalité spécialisée'),
                    ('MA2A', 'MA2A - Master en 120 crédits à finalité approfondie'),
                    ('MA2M', 'MA2M - Master en 180 ou 240 crédits'),
                    ('MACO', 'MACO - Master complémentaire'),
                    ('AESSB', "AESSB - Agrégation de l'enseignement secondaire supérieur (AESS)"),
                    ('CAPS', "CAPS - Certificat d'aptitude pédagogique approprié à l'enseignement supérieur (CAPAES)"),
                    ('FODO', 'FODO - Formations doctorales (Certificat de formation à la recherche)'),
                    ('DOCB', 'DOCB - Docteur'),
                    (
                        'CEMC',
                        'CEMC - Certificats de médecine clinique / '
                        'Certificats interuniversitaires de formation médicale spécialisée'
                    )
                ],
                max_length=40, null=True, verbose_name='Decree category'
            ),
        ),
    ]
