# Generated by Django 2.2.13 on 2020-12-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0548_auto_20201214_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrule',
            name='placeholder',
            field=models.CharField(blank=True, max_length=35, verbose_name='Placeholder'),
        ),
    ]
