# Generated by Django 2.2.13 on 2020-12-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0549_auto_20201215_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningcontaineryear',
            name='in_charge',
        ),
    ]
