# Generated by Django 2.2.13 on 2021-01-05 09:32

from django.db import migrations, models


def copy_other_remark_from_lu_to_luy(apps, schema_editor):
    LearningUnit = apps.get_model('base', 'LearningUnit')
    LearningUnitYear = apps.get_model('base', 'LearningUnitYear')
    lus = LearningUnit.objects.filter(other_remark__isnull=False)
    for lu in lus:
        luys = lu.learningunityear_set.all()
        for luy in luys:
            luy.other_remark = lu.other_remark
        LearningUnitYear.objects.bulk_update(luys, ['other_remark'])


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0549_auto_20201215_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunityear',
            name='other_remark',
            field=models.TextField(blank=True, null=True, verbose_name='Other remark (intended for publication)'),
        ),
        migrations.RunPython(copy_other_remark_from_lu_to_luy),
        migrations.RemoveField(
            model_name='learningunit',
            name='other_remark',
        )
    ]
