# Generated by Django 2.2.13 on 2021-01-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0550_auto_20201221_1024'),
        ('base', '0550_remove_learningcontaineryear_in_charge'),
    ]

    operations = [
    ]
