# Generated by Django 2.2.13 on 2021-01-08 11:18

from django.db import migrations

from base.models.enums import academic_calendar_type


def fix_title_academic_calendar(apps, shema_editor):
    """
    We will fix title of older academic calendar
    """
    AcademicCalendar = apps.get_model('base', 'academiccalendar')
    AcademicCalendar.objects.filter(reference=academic_calendar_type.EDUCATION_GROUP_EDITION).update(
        title="Préparation des formations"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0552_remarks_annualized'),
    ]

    operations = [
        migrations.RunPython(fix_title_academic_calendar)
    ]
