# Generated by Django 2.2.13 on 2021-02-02 17:00

import uuid
from typing import Iterable

from django.db import migrations
from django.db.models import Q, F, Subquery, OuterRef

from base.business.utils.model import model_to_dict_fk
from base.models.academic_year import AcademicYear
from base.models.enums import learning_unit_year_subtypes
from base.models.learning_component_year import LearningComponentYear
from base.models.learning_unit_year import LearningUnitYear
from cms.enums import entity_name
from cms.models.translated_text import TranslatedText


def _create_component(component: LearningComponentYear, new_learning_unit_year: LearningUnitYear):
    component_dict = model_to_dict_fk(
        component,
        exclude=['id', 'external_id', 'uuid', 'learning_unit_year', 'type', 'changed']
    )
    LearningComponentYear.objects.get_or_create(
        learning_unit_year=new_learning_unit_year,
        type=component.type,
        defaults={
            'uuid': uuid.uuid4(),
            **component_dict
        }
    )


def _create_learning_unit(ac_year: AcademicYear, luy: LearningUnitYear) -> LearningUnitYear:
    luy_dict = model_to_dict_fk(
        luy,
        exclude=['id', 'uuid', 'academic_year_id', 'learning_container_year_id', 'acronym', 'external_id', 'changed']
    )
    new_learning_unit_year = LearningUnitYear.objects.get_or_create(
        academic_year=ac_year,
        acronym=luy.acronym,
        defaults={
            'learning_container_year': LearningUnitYear.objects.get(
                academic_year=ac_year,
                acronym=luy.acronym[:-1]
            ).learning_container_year,
            'uuid': uuid.uuid4(),
            **luy_dict
        }
    )
    return new_learning_unit_year


def _create_cms(cms_qs: Iterable[TranslatedText], new_luy: LearningUnitYear):
    for cms in cms_qs:
        TranslatedText.objects.get_or_create(
            reference=new_luy.pk,
            text_label_id=cms.text_label_id,
            language=cms.language,
            entity=entity_name.LEARNING_UNIT_YEAR,
            defaults={'text': cms.text}
        )


def create_missing_partims(apps, schema_editor):
    partims = LearningUnitYear.objects.filter(
        subtype=learning_unit_year_subtypes.PARTIM,
    ).annotate(
        max_anac=Subquery(
            LearningUnitYear.objects.filter(
                learning_unit_id=OuterRef('learning_unit_id')
            ).order_by('-academic_year__year').values('academic_year__year')[:1]
        )
    ).filter(
        Q(max_anac__lt=F('learning_unit__end_year__year')) | (
                Q(learning_unit__end_year__isnull=True) & Q(max_anac__lt=2024)
        ),
        max_anac__gte=2019
    )
    for partim in partims:
        last_full_ue = LearningUnitYear.objects.filter(
            subtype=learning_unit_year_subtypes.FULL,
            learning_unit_id=partim.learning_container_year.learningunityear_set.get(
                subtype=learning_unit_year_subtypes.FULL
            ).learning_unit_id
        ).order_by('academic_year__year').last()
        for year in range(partim.max_anac + 1, last_full_ue.academic_year.year + 1):
            anac = AcademicYear.objects.get(year=year)
            new_partim = _create_learning_unit(anac, partim)
            for component in partim.learningcomponentyear_set.all():
                _create_component(component, new_partim)
                cms_qs = partim.translatedtext_set.all()
                _create_cms(cms_qs, new_partim)


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0557_learningunityear_other_remark_english'),
    ]

    operations = [
        migrations.RunPython(create_missing_partims)
    ]
