# Generated by Django 2.2.13 on 2021-02-02 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0557_learningunityear_other_remark_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitymanager',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_entitymanager_set', to='base.Person'),
        ),
    ]
