# Generated by Django 2.2.13 on 2021-01-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0558_auto_20210115_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningunit',
            name='other_remark',
        ),
    ]
