# Generated by Django 2.2.13 on 2021-02-16 15:43

from django.db import migrations
from django.db.models import Q
from django.utils import timezone

from base.models.education_group_year import EducationGroupYear
from education_group.models.group_year import GroupYear


def clean_titles(apps, schema_editor):
    problematic_egys = find_problematic_egys()

    print("Problematic EducationGroupYears: {}".format(len(problematic_egys)))
    for egy in problematic_egys:
        egy.title = egy.title.replace('\n', '')
        egy.title_english = egy.title_english.replace('\n', '')
        egy.changed = timezone.now()
        egy.save()
        print(str(egy.id))

    problematic_gys = find_problematic_gys()

    print("Problematic GroupYears: {}".format(len(problematic_gys)))

    for gy in problematic_gys:
        gy.title = gy.title.replace('\n', '')
        gy.title_english = gy.title_english.replace('\n', '')
        gy.changed = timezone.now()
        gy.save()
        print(str(gy.id))


def find_problematic_egys():
    return EducationGroupYear.objects.filter(
        Q(title__contains='\n') | Q(title_english__contains='\n')
    )


def find_problematic_gys():
    return GroupYear.objects.filter(
        Q(title_fr__contains='\n') | Q(title_en__contains='\n')
    )


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0559_fix_link_orders'),
    ]

    operations = [
        migrations.RunPython(clean_titles),
    ]
