# Generated by Django 2.2.13 on 2021-01-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0560_auto_20210120_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionconditionline',
            name='section',
            field=models.CharField(choices=[('ucl_bachelors', 'UCL Bachelors'), ('others_bachelors_french', 'Others Bachelors of the French speaking Community of Belgium'), ('bachelors_dutch', 'Bachelors of the Dutch speaking Community of Belgium'), ('foreign_bachelors', 'Foreign Bachelors'), ('graduates', 'Graduates'), ('masters', 'Masters')], max_length=32),
        ),
    ]
