# Generated by Django 2.2.13 on 2021-02-15 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0567_auto_20210211_0843'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academiccalendar',
            unique_together=set(),
        ),
    ]
