# Generated by Django 2.2.13 on 2021-03-04 14:42
import datetime

from django.db import migrations
from django.db.models import Q
from django.utils import timezone

from base.models.academic_year import AcademicYear
from base.models.education_group import EducationGroup
from base.models.education_group_year import EducationGroupYear
from education_group.models.group import Group
from education_group.models.group_year import GroupYear

EDUCATION_GROUP_START_YEARS = {
    '10378': 1984,
    '10703': 1984,
    '10381': 1988,
    '10740': 1984,
    '10741': 1984,
    '10431': 1984,
    '10545': 1984,
    '10600': 1984,
    '10546': 1984,
    '10382': 1984,
    '10383': 1994,
    '10384': 1994,
    '10742': 1994,
    '10743': 1994,
    '10485': 1984,
    '10704': 1984,
    '10385': 1984,
    '10547': 1984,
    '10486': 1984,
    '10487': 1984,
    '10602': 1988,
    '10603': 1984,
    '10386': 1988,
    '10746': 1984,
    '10488': 1984,
    '10387': 1984,
    '10388': 1984,
    '10706': 1984,
    '10605': 1984,
    '10708': 1984,
    '10709': 1968,
    '10655': 1984,
    '10748': 1984,
    '10489': 1984,
    '10656': 1984,
    '10606': 1984,
    '10549': 1984,
    '10607': 1988,
    '10434': 1995,
    '10490': 1984,
    '10491': 1988,
    '10608': 1984,
    '10750': 1997,
    '10550': 1984,
    '10751': 1984,
    '10492': 1988,
    '10609': 1984,
    '10752': 1984,
    '10390': 1987,
    '10435': 1987,
    '10710': 1984,
    '10711': 1984,
    '10657': 1984,
    '10660': 1984,
    '10918': 2004,
    '10860': 2004,
    '10858': 2004,
    '10921': 2005,
    '10596': 1984,
    '10542': 1983,
    '11551': 1984,
    '10960': 1984,
    '10805': 1984,
    '11072': 1984,

}


def clean_start_years(apps, schema_editor):
    problematic_egys = find_problematic_egys()
    print("Problematic EducationGroupYears: {}".format(len(problematic_egys)))
    clean_start_years_from_data_dict(problematic_egys)
    problematic_gys = find_problematic_gys()
    print("Problematic EducationGroupYears: {}".format(len(problematic_gys)))
    clean_start_years_from_egys(problematic_gys)


def clean_start_years_from_egys(problematic_gys):
    groups_to_update = []
    for gy in problematic_gys:
        egy = EducationGroupYear.objects.filter(
            partial_acronym=gy.partial_acronym
        ).order_by('academic_year__year').last()
        print("Changing start year of {} from {} to {}".format(
            gy.partial_acronym,
            gy.group.start_year.year,
            egy.education_group.start_year.year
        ))
        gy.group.start_year_id = egy.education_group.start_year_id
        gy.group.changed = timezone.now()
        groups_to_update.append(gy.group)
    Group.objects.bulk_update(groups_to_update, ['start_year_id', 'changed'], batch_size=1000)


def clean_start_years_from_data_dict(problematic_egys):
    education_group_to_update = []
    group_to_update = []
    for egy in problematic_egys:
        education_group = egy.education_group
        start_year = EDUCATION_GROUP_START_YEARS[str(education_group.id)]
        print("Changing start year of {} from {} to {}".format(
            egy.acronym,
            education_group.start_year.year,
            start_year
        ))
        anac, _ = AcademicYear.objects.get_or_create(
            year=start_year,
            defaults={
                'start_date': datetime.datetime(start_year, 7, 1),
                'end_date': datetime.datetime(start_year + 1, 10, 31)
            }
        )
        education_group.start_year_id = anac.id
        education_group.changed = timezone.now()
        education_group_to_update.append(education_group)

        group = egy.educationgroupversion_set.get(
            Q(version_name='') | Q(version_name__isnull=True),
            is_transition=False
        ).root_group.group
        group.start_year_id = anac.id
        group.changed = timezone.now()
        group_to_update.append(group)
    EducationGroup.objects.bulk_update(education_group_to_update, ['start_year_id', 'changed'], batch_size=1000)
    Group.objects.bulk_update(group_to_update, ['start_year_id', 'changed'], batch_size=1000)


def find_problematic_egys():
    return EducationGroupYear.objects.filter(
        education_group__start_year__year=1900
    ).order_by('education_group').distinct('education_group')


def find_problematic_gys():
    return GroupYear.objects.filter(
        group__start_year__year=1900
    ).order_by('group').distinct('group')


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0567_auto_20210211_0843'),
    ]

    operations = [
        migrations.RunPython(clean_start_years),
    ]
