# Generated by Django 2.2.13 on 2021-03-09 08:17

from django.db import migrations
from django.db.models import F
from django.utils import timezone

from base.models.education_group import EducationGroup
from base.models.education_group_year import EducationGroupYear
from education_group.models.group import Group
from education_group.models.group_year import GroupYear


def clean_end_years(apps, schema_editor):
    problematic_gys = find_problematic_gys()
    print("Problematic GroupYears: {}".format(len(problematic_gys)))
    group_to_update = []
    for gy in problematic_gys:
        print(
            "Group Year {} : changing end year from {} to {}".format(
                gy.partial_acronym,
                gy.group.end_year.year,
                gy.academic_year.year
            )
        )
        gy.group.end_year_id = gy.academic_year_id
        gy.group.changed = timezone.now()
        group_to_update.append(gy.group)
    Group.objects.bulk_update(group_to_update, ['end_year_id', 'changed'], batch_size=1000)

    problematic_egys = find_problematic_egys()
    print("Problematic EducationGroupYears: {}".format(len(problematic_egys)))
    education_group_to_update = []
    for egy in problematic_egys:
        print(
            "Education Group Year {} : changing end year from {} to {}".format(
                egy.partial_acronym,
                egy.education_group.end_year.year,
                egy.academic_year.year
            )
        )
        egy.education_group.end_year_id = egy.academic_year_id
        egy.education_group.changed = timezone.now()
        education_group_to_update.append(egy.education_group)
    EducationGroup.objects.bulk_update(education_group_to_update, ['end_year_id', 'changed'], batch_size=1000)


def find_problematic_gys():
    return GroupYear.objects.filter(
        group__end_year__year__lt=F('academic_year__year')
    ).exclude(
        education_group_type__category='GROUP'
    ).order_by(
        'group_id',
        '-academic_year__year'
    ).distinct('group_id')


def find_problematic_egys():
    return EducationGroupYear.objects.filter(
        education_group__end_year__year__lt=F('academic_year__year')
    ).order_by(
        'education_group_id',
        '-academic_year__year'
    ).distinct('education_group_id')


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0567_auto_20210211_0843'),
    ]

    operations = [
        migrations.RunPython(clean_end_years),
    ]
