# Generated by Django 2.2.13 on 2021-03-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0569_auto_20210225_1350'),
        ('base', '0569_update_is_mandatory_field_when_empty_skeleton'),
    ]

    operations = [
    ]
