# Generated by Django 2.2.13 on 2021-03-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0570_merge_20210303_1036'),
        ('base', '0570_studentspecificprofile_comment'),
    ]

    operations = [
    ]
