# Generated by Django 2.2.13 on 2021-03-05 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0572_auto_20210309_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hops',
            name='ares_graca',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='ARES-GRACA'),
        ),
    ]
