# Generated by Django 2.2.13 on 2021-03-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0573_auto_20210305_1005'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academiccalendar',
            unique_together={('data_year', 'title')},
        ),
    ]
