# Generated by Django 2.2.13 on 2021-03-29 11:23

from django.db import migrations
from django.utils import timezone

from base.models.enums.education_group_types import TrainingType


def set_web_re_registration_to_false(apps, schema_editor):
    EducationGroupYear = apps.get_model('base', 'EducationGroupYear')
    concerned_egys = _get_concerned_egys(EducationGroupYear)
    print("Problematic EducationGroupYears : {}".format(len(concerned_egys)))
    for egy in concerned_egys:
        print("Set web re registration of {} - {} to False".format(egy.acronym, egy.academic_year.year))
        egy.web_re_registration = False
        egy.changed = timezone.now()
    EducationGroupYear.objects.bulk_update(concerned_egys, ['web_re_registration', 'changed'], batch_size=1000)


def _get_concerned_egys(egy):
    return egy.objects.filter(
        academic_year__year__gte=2019,
        education_group_type__name__in=TrainingType.root_master_2m_types(),
        web_re_registration=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0574_auto_20210316_1319'),
    ]

    operations = [
        migrations.RunPython(set_web_re_registration_to_false)
    ]
