# Generated by Django 2.2.13 on 2021-03-16 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0577_auto_20210201_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiccalendar',
            name='description',
        ),
        migrations.RemoveField(
            model_name='academiccalendar',
            name='highlight_description',
        ),
        migrations.RemoveField(
            model_name='academiccalendar',
            name='highlight_shortcut',
        ),
        migrations.RemoveField(
            model_name='academiccalendar',
            name='highlight_title',
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='data_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='reference',
            field=models.CharField(choices=[('DELIBERATION', 'Deliberation'), ('DISSERTATION_SUBMISSION', 'Dissertation submission'), ('EXAM_ENROLLMENTS', 'Exam enrollments'), ('SCORES_EXAM_DIFFUSION', 'Scores diffusion'), ('SCORES_EXAM_SUBMISSION', 'Scores exam submission'), ('TEACHING_CHARGE_APPLICATION', 'Application for vacant courses'), ('ACCESS_SCHEDULE_CALENDAR', 'Access schedule calendar'), ('COURSE_ENROLLMENT', 'Course enrollment'), ('SUMMARY_COURSE_SUBMISSION', 'Summary course submission'), ('SUMMARY_COURSE_SUBMISSION_FORCE_MAJEURE', 'Summary course submission force majeure'), ('EDUCATION_GROUP_SWITCH', 'Education group switch'), ('EDUCATION_GROUP_EDITION', 'Education group edition'), ('EDUCATION_GROUP_EXTENDED_DAILY_MANAGEMENT', 'Education group extended daily management'), ('EDUCATION_GROUP_LIMITED_DAILY_MANAGEMENT', 'Education group limited daily management'), ('LEARNING_UNIT_EXTENDED_PROPOSAL_MANAGEMENT', 'Extended proposal management'), ('LEARNING_UNIT_LIMITED_PROPOSAL_MANAGEMENT', 'Limited proposal management')], db_index=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
