# Generated by Django 2.2.13 on 2021-03-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0578_auto_20210316_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiccalendar',
            name='academic_year',
        ),
    ]
