# Generated by Django 2.2.13 on 2021-03-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0578_studentspecificprofile_translation'),
        ('base', '0579_remove_academiccalendar_academic_year'),
    ]

    operations = [
    ]
