# Generated by Django 2.2.13 on 2021-03-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0581_auto_20210317_1620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonEntity',
        ),
    ]
