# Generated by Django 2.2.13 on 2021-04-19 09:54

from django.db import migrations


def remove_unused_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    groups_to_remove = ("administrators", "authorisations_manager", "executive", "expert_users",)
    Group.objects.filter(name__in=groups_to_remove).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0583_auto_20210324_0954'),
    ]

    operations = [
        migrations.RunPython(remove_unused_groups, migrations.RunPython.noop)
    ]
