# Generated by Django 2.2.13 on 2021-04-20 08:45

from django.db import migrations


def assign_specific_permissions_and_remove_unused_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    admin_grp = Group.objects.filter(name="administrator_for_user").first()
    if admin_grp:
        permissions_admin_grp = admin_grp.permissions.all()
        for user in admin_grp.user_set.all():
            user.user_permissions.add(*permissions_admin_grp)
        admin_grp.delete()

    Group.objects.filter(name="student_update_UE_AA").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0584_auto_20210419_0954'),
    ]

    operations = [
        migrations.RunPython(assign_specific_permissions_and_remove_unused_groups, migrations.RunPython.noop)
    ]
