# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-14 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0011_auto_20160610_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantmandate',
            name='state',
            field=models.CharField(choices=[('DECLINED', 'Declined'), ('TO_DO', 'To do'), ('TRTS', 'Trts'), ('PHD_SUPERVISOR', 'PhD supervisor'), ('RESEARCH', 'Research'), ('SUPERVISION', 'Supervision'), ('VICE_RECTOR', 'Vice rector'), ('DONE', 'Done')], default='TO_DO', max_length=20),
        ),
    ]
