# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 07:49
from __future__ import unicode_literals

import assistant.models.assistant_document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0014_tutoringlearningunityear_learning_unit_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantdocument',
            name='file',
            field=models.FileField(default=1, upload_to=assistant.models.assistant_document.get_upload_file_name),
            preserve_default=False,
        ),
    ]
